### PR TITLE
fixed SQL Server schema name bug that prevented from getting tables

### PR DESCRIPTION
**Pull request by vrcod**
fixes issue [#1767](https://github.com/slick/slick/issues/1767)

### CODE REVIEW

**Comment by cvogt** [comment]
Happy to merge this. Can we create a great for this?

**Comment by vrcod** [comment]
@cvogt Sorry, what is a "great" in this case?

**Comment by cvogt** [comment]
Sorry, I meant a "test" :)

**Comment by vrcod** [comment]
@cvogt But if this is just a small fix, don't existing tests already cover it? Travis seems to pass, not sure what went wrong with appveyor though. If not then I can give it a shot, if someone points me to the right direction.

**Comment by sukeyisme** [comment]
merged?

**Comment by hvesalai** [comment]
This PR is failing two tests: 

```
[error] Test com.typesafe.slick.testkit.tests.ModelBuilderTest.test[sqlserver2012-jtds] failed: java.lang.AssertionError: List(Table(QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Vector(Column(type,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Clob,false,Set(SqlType(varchar))), Column(Boolean,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Boolean,false,Set(SqlType(bit), Default(true))), Column(Byte,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Short,false,Set(SqlType(smallint))), Column(Short,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Short,false,Set(SqlType(smallint))), Column(Int,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int), Default(-5))), Column(Long,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Long,false,Set(SqlType(bigint), Default(5))), Column(Float,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Float,false,Set(SqlType(real), Default(9.999))), Column(Double,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Double,false,Set(SqlType(float), Default(9.999))), Column(String,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),String,false,Set(SqlType(varchar), Length(254,true), Default(someDefaultString))), Column(java_sql_Date,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Date,false,Set(SqlType(date))), Column(java_sql_Time,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Time,false,Set(SqlType(time))), Column(java_sql_Timestamp,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Timestamp,false,Set(SqlType(datetime))), Column(java_sql_Blob,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Blob,false,Set(SqlType(varbinary))), Column(None_Int,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Int,true,Set(SqlType(int), Default(None))), Column(Option_Boolean,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Boolean,true,Set(SqlType(bit), Default(Some(true)))), Column(Option_Byte,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Short,true,Set(SqlType(smallint))), Column(Option_Short,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Short,true,Set(SqlType(smallint))), Column(Option_Int,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Int,true,Set(SqlType(int), Default(Some(5)))), Column(Option_Long,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Long,true,Set(SqlType(bigint), Default(Some(-5)))), Column(Option_Float,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Float,true,Set(SqlType(real), Default(Some(9.999)))), Column(Option_Double,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Double,true,Set(SqlType(float), Default(Some(9.999)))), Column(Option_String,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),String,true,Set(SqlType(varchar), Length(254,true), Default(Some(someDefaultString)))), Column(Option_java_sql_Date,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Date,true,Set(SqlType(date))), Column(Option_java_sql_Time,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Time,true,Set(SqlType(time))), Column(Option_java_sql_Timestamp,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Timestamp,true,Set(SqlType(datetime))), Column(Option_java_sql_Blob,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Blob,true,Set(SqlType(varbinary)))),Some(PrimaryKey(Some(PK),QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Vector(Column(Int,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int), Default(-5))), Column(Long,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Long,false,Set(SqlType(bigint), Default(5)))),Set())),ArrayBuffer(),ArrayBuffer(),Set()), Table(QualifiedName(categories,Some(dbo),Some(slicktest)),Vector(Column(id,QualifiedName(categories,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int identity), AutoInc, PrimaryKey)), Column(name,QualifiedName(categories,Some(dbo),Some(slicktest)),String,false,Set(SqlType(varchar), Length(123,true)))),None,ArrayBuffer(),ArrayBuffer(Index(Some(IDX_NAME),QualifiedName(categories,Some(dbo),Some(slicktest)),Vector(Column(name,QualifiedName(categories,Some(dbo),Some(slicktest)),String,false,Set(SqlType(varchar), Length(123,true)))),false,Set())),Set()), Table(QualifiedName(default_test,Some(dbo),Some(slicktest)),Vector(Column(some_bool,QualifiedName(default_test,Some(dbo),Some(slicktest)),Boolean,false,Set(SqlType(bit))), Column(some_bool_default_true,QualifiedName(default_test,Some(dbo),Some(slicktest)),Boolean,false,Set(SqlType(bit), Default(true))), Column(some_bool_default_false,QualifiedName(default_test,Some(dbo),Some(slicktest)),Boolean,false,Set(SqlType(bit), Default(false))), Column(some_bool_option,QualifiedName(default_test,Some(dbo),Some(slicktest)),Boolean,true,Set(SqlType(bit))), Column(some_bool_option_default_some,QualifiedName(default_test,Some(dbo),Some(slicktest)),Boolean,true,Set(SqlType(bit), Default(Some(true)))), Column(some_bool_option_default_none,QualifiedName(default_test,Some(dbo),Some(slicktest)),Boolean,true,Set(SqlType(bit), Default(None))), Column(some_string,QualifiedName(default_test,Some(dbo),Some(slicktest)),java.sql.Clob,false,Set(SqlType(varchar))), Column(some_string_default_non_empty,QualifiedName(default_test,Some(dbo),Some(slicktest)),String,false,Set(SqlType(varchar), Length(254,true), Default(bar))), Column(some_string_default_empty,QualifiedName(default_test,Some(dbo),Some(slicktest)),String,false,Set(SqlType(varchar), Length(254,true), Default())), Column(some_string_option,QualifiedName(default_test,Some(dbo),Some(slicktest)),java.sql.Clob,true,Set(SqlType(varchar))), Column(str_option_default_empty,QualifiedName(default_test,Some(dbo),Some(slicktest)),String,true,Set(SqlType(varchar), Length(254,true), Default(Some()))), Column(str_option_default_non_empty,QualifiedName(default_test,Some(dbo),Some(slicktest)),String,true,Set(SqlType(varchar), Length(254,true), Default(Some(foo)))), Column(str_option_default_none,QualifiedName(default_test,Some(dbo),Some(slicktest)),java.sql.Clob,true,Set(SqlType(varchar), Default(None)))),None,ArrayBuffer(),ArrayBuffer(),Set()), Table(QualifiedName(no_default_test,Some(dbo),Some(slicktest)),Vector(Column(int,QualifiedName(no_default_test,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int))), Column(stringOption,QualifiedName(no_default_test,Some(dbo),Some(slicktest)),java.sql.Clob,true,Set(SqlType(varchar))), Column(stringOptionDefaultNone,QualifiedName(no_default_test,Some(dbo),Some(slicktest)),java.sql.Clob,true,Set(SqlType(varchar), Default(None)))),None,ArrayBuffer(),ArrayBuffer(),Set()), Table(QualifiedName(posts,Some(dbo),Some(slicktest)),Vector(Column(id,QualifiedName(posts,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int))), Column(title,QualifiedName(posts,Some(dbo),Some(slicktest)),String,false,Set(SqlType(char), Length(99,false))), Column(category,QualifiedName(posts,Some(dbo),Some(slicktest)),Int,true,Set(SqlType(int), Default(Some(531)))), Column(some_bool,QualifiedName(posts,Some(dbo),Some(slicktest)),Boolean,false,Set(SqlType(bit), Default(true))), Column(some_string,QualifiedName(posts,Some(dbo),Some(slicktest)),String,false,Set(SqlType(varchar), Length(111,true)))),Some(PrimaryKey(Some(posts_pk),QualifiedName(posts,Some(dbo),Some(slicktest)),Vector(Column(id,QualifiedName(posts,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int))), Column(title,QualifiedName(posts,Some(dbo),Some(slicktest)),String,false,Set(SqlType(char), Length(99,false)))),Set())),ArrayBuffer(ForeignKey(Some(category_fk),QualifiedName(posts,Some(dbo),Some(slicktest)),Vector(Column(category,QualifiedName(posts,Some(dbo),Some(slicktest)),Int,true,Set(SqlType(int), Default(Some(531))))),QualifiedName(categories,Some(dbo),Some(slicktest)),Vector(Column(id,QualifiedName(categories,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int identity), AutoInc, PrimaryKey))),Restrict,Restrict,Set())),ArrayBuffer(),Set()), Table(QualifiedName(trace_xe_action_map,Some(sys),Some(slicktest)),Vector(Column(trace_column_id,QualifiedName(trace_xe_action_map,Some(sys),Some(slicktest)),Short,false,Set(SqlType(smallint))), Column(package_name,QualifiedName(trace_xe_action_map,Some(sys),Some(slicktest)),String,false,Set(SqlType(nvarchar), Length(60,true))), Column(xe_action_name,QualifiedName(trace_xe_action_map,Some(sys),Some(slicktest)),String,false,Set(SqlType(nvarchar), Length(60,true)))),None,ArrayBuffer(),ArrayBuffer(),Set()), Table(QualifiedName(trace_xe_event_map,Some(sys),Some(slicktest)),Vector(Column(trace_event_id,QualifiedName(trace_xe_event_map,Some(sys),Some(slicktest)),Short,false,Set(SqlType(smallint))), Column(package_name,QualifiedName(trace_xe_event_map,Some(sys),Some(slicktest)),String,false,Set(SqlType(nvarchar), Length(60,true))), Column(xe_event_name,QualifiedName(trace_xe_event_map,Some(sys),Some(slicktest)),String,false,Set(SqlType(nvarchar), Length(60,true)))),None,ArrayBuffer(),ArrayBuffer(),Set())) expected:<5> but was:<7>, took 3.047 sec
[error]     at com.typesafe.slick.testkit.tests.ModelBuilderTest$$anonfun$test$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$7$$anonfun$apply$11$$anonfun$apply$14$$anonfun$apply$18$$anonfun$apply$19.apply(ModelBuilderTest.scala:145)
[error]     at com.typesafe.slick.testkit.tests.ModelBuilderTest$$anonfun$test$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$7$$anonfun$apply$11$$anonfun$apply$14$$anonfun$apply$18$$anonfun$apply$19.apply(ModelBuilderTest.scala:142)
[error]     at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:43)
[error]     at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:43)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:147)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:147)
[error]     at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
[error]     at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
[error]     at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[error]     at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
[error]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
[error]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
[error]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
```

and 

```
[error] Test com.typesafe.slick.testkit.tests.ModelBuilderTest.test[sqlserver2014-jtds] failed: java.lang.AssertionError: List(Table(QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Vector(Column(type,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Clob,false,Set(SqlType(varchar))), Column(Boolean,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Boolean,false,Set(SqlType(bit), Default(true))), Column(Byte,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Short,false,Set(SqlType(smallint))), Column(Short,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Short,false,Set(SqlType(smallint))), Column(Int,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int), Default(-5))), Column(Long,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Long,false,Set(SqlType(bigint), Default(5))), Column(Float,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Float,false,Set(SqlType(real), Default(9.999))), Column(Double,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Double,false,Set(SqlType(float), Default(9.999))), Column(String,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),String,false,Set(SqlType(varchar), Length(254,true), Default(someDefaultString))), Column(java_sql_Date,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Date,false,Set(SqlType(date))), Column(java_sql_Time,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Time,false,Set(SqlType(time))), Column(java_sql_Timestamp,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Timestamp,false,Set(SqlType(datetime))), Column(java_sql_Blob,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Blob,false,Set(SqlType(varbinary))), Column(None_Int,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Int,true,Set(SqlType(int), Default(None))), Column(Option_Boolean,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Boolean,true,Set(SqlType(bit), Default(Some(true)))), Column(Option_Byte,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Short,true,Set(SqlType(smallint))), Column(Option_Short,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Short,true,Set(SqlType(smallint))), Column(Option_Int,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Int,true,Set(SqlType(int), Default(Some(5)))), Column(Option_Long,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Long,true,Set(SqlType(bigint), Default(Some(-5)))), Column(Option_Float,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Float,true,Set(SqlType(real), Default(Some(9.999)))), Column(Option_Double,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Double,true,Set(SqlType(float), Default(Some(9.999)))), Column(Option_String,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),String,true,Set(SqlType(varchar), Length(254,true), Default(Some(someDefaultString)))), Column(Option_java_sql_Date,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Date,true,Set(SqlType(date))), Column(Option_java_sql_Time,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Time,true,Set(SqlType(time))), Column(Option_java_sql_Timestamp,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Timestamp,true,Set(SqlType(datetime))), Column(Option_java_sql_Blob,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),java.sql.Blob,true,Set(SqlType(varbinary)))),Some(PrimaryKey(Some(PK),QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Vector(Column(Int,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int), Default(-5))), Column(Long,QualifiedName(TYPE_TEST,Some(dbo),Some(slicktest)),Long,false,Set(SqlType(bigint), Default(5)))),Set())),ArrayBuffer(),ArrayBuffer(),Set()), Table(QualifiedName(categories,Some(dbo),Some(slicktest)),Vector(Column(id,QualifiedName(categories,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int identity), AutoInc, PrimaryKey)), Column(name,QualifiedName(categories,Some(dbo),Some(slicktest)),String,false,Set(SqlType(varchar), Length(123,true)))),None,ArrayBuffer(),ArrayBuffer(Index(Some(IDX_NAME),QualifiedName(categories,Some(dbo),Some(slicktest)),Vector(Column(name,QualifiedName(categories,Some(dbo),Some(slicktest)),String,false,Set(SqlType(varchar), Length(123,true)))),false,Set())),Set()), Table(QualifiedName(default_test,Some(dbo),Some(slicktest)),Vector(Column(some_bool,QualifiedName(default_test,Some(dbo),Some(slicktest)),Boolean,false,Set(SqlType(bit))), Column(some_bool_default_true,QualifiedName(default_test,Some(dbo),Some(slicktest)),Boolean,false,Set(SqlType(bit), Default(true))), Column(some_bool_default_false,QualifiedName(default_test,Some(dbo),Some(slicktest)),Boolean,false,Set(SqlType(bit), Default(false))), Column(some_bool_option,QualifiedName(default_test,Some(dbo),Some(slicktest)),Boolean,true,Set(SqlType(bit))), Column(some_bool_option_default_some,QualifiedName(default_test,Some(dbo),Some(slicktest)),Boolean,true,Set(SqlType(bit), Default(Some(true)))), Column(some_bool_option_default_none,QualifiedName(default_test,Some(dbo),Some(slicktest)),Boolean,true,Set(SqlType(bit), Default(None))), Column(some_string,QualifiedName(default_test,Some(dbo),Some(slicktest)),java.sql.Clob,false,Set(SqlType(varchar))), Column(some_string_default_non_empty,QualifiedName(default_test,Some(dbo),Some(slicktest)),String,false,Set(SqlType(varchar), Length(254,true), Default(bar))), Column(some_string_default_empty,QualifiedName(default_test,Some(dbo),Some(slicktest)),String,false,Set(SqlType(varchar), Length(254,true), Default())), Column(some_string_option,QualifiedName(default_test,Some(dbo),Some(slicktest)),java.sql.Clob,true,Set(SqlType(varchar))), Column(str_option_default_empty,QualifiedName(default_test,Some(dbo),Some(slicktest)),String,true,Set(SqlType(varchar), Length(254,true), Default(Some()))), Column(str_option_default_non_empty,QualifiedName(default_test,Some(dbo),Some(slicktest)),String,true,Set(SqlType(varchar), Length(254,true), Default(Some(foo)))), Column(str_option_default_none,QualifiedName(default_test,Some(dbo),Some(slicktest)),java.sql.Clob,true,Set(SqlType(varchar), Default(None)))),None,ArrayBuffer(),ArrayBuffer(),Set()), Table(QualifiedName(no_default_test,Some(dbo),Some(slicktest)),Vector(Column(int,QualifiedName(no_default_test,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int))), Column(stringOption,QualifiedName(no_default_test,Some(dbo),Some(slicktest)),java.sql.Clob,true,Set(SqlType(varchar))), Column(stringOptionDefaultNone,QualifiedName(no_default_test,Some(dbo),Some(slicktest)),java.sql.Clob,true,Set(SqlType(varchar), Default(None)))),None,ArrayBuffer(),ArrayBuffer(),Set()), Table(QualifiedName(posts,Some(dbo),Some(slicktest)),Vector(Column(id,QualifiedName(posts,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int))), Column(title,QualifiedName(posts,Some(dbo),Some(slicktest)),String,false,Set(SqlType(char), Length(99,false))), Column(category,QualifiedName(posts,Some(dbo),Some(slicktest)),Int,true,Set(SqlType(int), Default(Some(531)))), Column(some_bool,QualifiedName(posts,Some(dbo),Some(slicktest)),Boolean,false,Set(SqlType(bit), Default(true))), Column(some_string,QualifiedName(posts,Some(dbo),Some(slicktest)),String,false,Set(SqlType(varchar), Length(111,true)))),Some(PrimaryKey(Some(posts_pk),QualifiedName(posts,Some(dbo),Some(slicktest)),Vector(Column(id,QualifiedName(posts,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int))), Column(title,QualifiedName(posts,Some(dbo),Some(slicktest)),String,false,Set(SqlType(char), Length(99,false)))),Set())),ArrayBuffer(ForeignKey(Some(category_fk),QualifiedName(posts,Some(dbo),Some(slicktest)),Vector(Column(category,QualifiedName(posts,Some(dbo),Some(slicktest)),Int,true,Set(SqlType(int), Default(Some(531))))),QualifiedName(categories,Some(dbo),Some(slicktest)),Vector(Column(id,QualifiedName(categories,Some(dbo),Some(slicktest)),Int,false,Set(SqlType(int identity), AutoInc, PrimaryKey))),Restrict,Restrict,Set())),ArrayBuffer(),Set()), Table(QualifiedName(trace_xe_action_map,Some(sys),Some(slicktest)),Vector(Column(trace_column_id,QualifiedName(trace_xe_action_map,Some(sys),Some(slicktest)),Short,false,Set(SqlType(smallint))), Column(package_name,QualifiedName(trace_xe_action_map,Some(sys),Some(slicktest)),String,false,Set(SqlType(nvarchar), Length(60,true))), Column(xe_action_name,QualifiedName(trace_xe_action_map,Some(sys),Some(slicktest)),String,false,Set(SqlType(nvarchar), Length(60,true)))),None,ArrayBuffer(),ArrayBuffer(),Set()), Table(QualifiedName(trace_xe_event_map,Some(sys),Some(slicktest)),Vector(Column(trace_event_id,QualifiedName(trace_xe_event_map,Some(sys),Some(slicktest)),Short,false,Set(SqlType(smallint))), Column(package_name,QualifiedName(trace_xe_event_map,Some(sys),Some(slicktest)),String,false,Set(SqlType(nvarchar), Length(60,true))), Column(xe_event_name,QualifiedName(trace_xe_event_map,Some(sys),Some(slicktest)),String,false,Set(SqlType(nvarchar), Length(60,true)))),None,ArrayBuffer(),ArrayBuffer(),Set())) expected:<5> but was:<7>, took 3.359 sec
[error]     at com.typesafe.slick.testkit.tests.ModelBuilderTest$$anonfun$test$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$7$$anonfun$apply$11$$anonfun$apply$14$$anonfun$apply$18$$anonfun$apply$19.apply(ModelBuilderTest.scala:145)
[error]     at com.typesafe.slick.testkit.tests.ModelBuilderTest$$anonfun$test$1$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$7$$anonfun$apply$11$$anonfun$apply$14$$anonfun$apply$18$$anonfun$apply$19.apply(ModelBuilderTest.scala:142)
[error]     at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:43)
[error]     at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:43)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:147)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:147)
[error]     at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
[error]     at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
[error]     at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[error]     at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
[error]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
[error]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
[error]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

@vrcod can you see what is going on.

**Comment by vrcod** [comment]
@hvesalai I don't know why appveyor buid is failing, because travis build is fine and also if I run the exact command that appveyor runs for tests (`sbt testkit/test:test`) locally - every single test passes. How are you running these tests that they are failing?

**Comment by hvesalai** [comment]
I don't know much about the AppVeyor, but I think it is running some sqlserver2014 tests. Are those being run when you run it from your own console?

**Comment by hvesalai** [comment]
Just FYI: I did re-run the AppVeyor build, but the result is the same.

**Comment by vrcod** [comment]
I think I get it now, unlike travis appveyor runs windows specific stuff alongside all other tests, that's why those two tests are failing. Unfortunately I don't have access to MS stack, so can't really properly fix these tests. If there's someone else with MS stack they should try this fix - it's only a one liner. I'm closing this pull request.

**Comment by hvesalai** [comment]
@vrcod Here is why it was originally coded this way by 

@smootoo 

```
For SqlServer, schemas and users aren’t necessarily the same thing, but after SqlServer2008, there are system tables that come back from a query for tables that doesn’t filter by schema. The defaultTables method seems to be intended for list all the tables associated with the current connection and so when system tables come back, tests start to fail.
```

**Comment by hvesalai** [comment]
I think the correct solution would be to get all tables and then filter out the `sys` tables

**Comment by vrcod** [comment]
@hvesalai Thanks for the suggestion, seems to have worked, let's hope it will stick.

**Pull request merged**
