### PR TITLE
Updated MySQL jdbc driver to 8.0.x

### PR DESCRIPTION
**Pull request by WellingR**
I have updated the MySQL jdbc driver to the latest version. This resolves the huge load of "SSL connection" warnings in the travis output which were introduced after #2013 was merged.

Initially the tests failed, and it appears that issue #2002 was reproduced. This issue seems to have been caused by https://bugs.mysql.com/bug.php?id=93444

The real cause is that the client and the server do not use the correct timezone. It appears that it is important for the mysql jdbc driver to know the timezone. Therefore I have configured the `serverTimezone` parameter in the jdbc url for mysql.

### CODE REVIEW

**Comment by WellingR** [comment]
Question:
Since the tests fail using the latest MySQL driver (which is the recommended version for all supported MySQL databases, see [this link](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-versions.html)), should we fix the test so that Slick works fine using the latest driver, even though this might mean that these same tests might no longer work using the "5.1.x" driver version?

Testing and supporting both driver versions sounds like a good idea, however, as the drivers provide different versions of the same classes, this means that we need to do some ugly and hacking classloading magic to be able to test both versions.

My proposal would be to fix the tests, and document that Slick does NOT support the 5.1.x driver anymore starting from Slick 3.4.0

**Comment by WellingR** [comment]
The issue we are having seems to be caused by https://bugs.mysql.com/bug.php?id=93444

We are using an odd timezone in our tests to be able to find timezone related bugs. It seems that the latest mysql driver does not support this use case.

**Comment by WellingR** [comment]
Rebased on master.
As part of the latest change I configured `serverTimezone` parameter in the jdbc url, which seems to resolve the issue I had. I think that this means that #2002 is a configuration issue, and therefore not an actual bug in slick.

We may need to add some documentation that MySQL users need to configure the `serverTimezone` in case the client and server do not have the same timezone configured

**Comment by felipebonezi** [comment]
@WellingR hey, did you test with MySql 8.0?
When I run the `HelloSlick Project` isn't working because the DDL logic is creating the schema with quotes which is not allowed. 

BTW, I started to fix the #2002 issue and didn't see this PR.
I was looking at the `PostgresProfile` and saw that they use a better code structure and refactor the `MySQLProfile`.

**Comment by WellingR** [comment]
It's been a while ago, but it could be that I only tested this with MySql 5.
I am sure I ran the tests using travis. However according to the [travis documentation](https://docs.travis-ci.com/user/database-setup/#mysql) version 5.x is used.

**Comment by SethTisue** [comment]
if this is still relevant, rebase on current master? then we can try again to find a reviewer

**Comment by SethTisue** [comment]
thank you @WellingR!

**Pull request merged**
