### PR TITLE
allow to set code generator class dynamically

### PR DESCRIPTION
**Pull request by mendrik**
for issue #1747

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @mendrik,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by cvogt** [comment]
Nice! How exactly is this supposed to be used? Would it allow to simplify the example project? https://github.com/slick/slick-codegen-customization-example

**Comment by mendrik** [comment]
I'll change the docs also, will add example there.

**Comment by mendrik** [comment]
Or actually maybe rather here:
```
slickGenerate := {
    val dbName = "mydb"
    val userName = "user"
    val password = "mypassword"
    val url = s"jdbc:mysql://localhost:3306/$dbName?autoReconnect=true&useSSL=false&nullNamePatternMatchesAll=true"
    val jdbcDriver = "com.mysql.cj.jdbc.Driver"
    val slickDriver = "slick.jdbc.MySQLProfile"
    val targetPackageName = "database"
    val outputDir = (sourceManaged in Compile).value.getPath // place generated files in sbt's managed sources folder
    val fname = outputDir + s"/$targetPackageName/Tables.scala"
    println(s"\nauto-generating slick source for database schema at $url...")
    println(s"output source file file: file://$fname\n")
    (runner in Compile).value.run("slick.codegen.SourceCodeGenerator",
        (dependencyClasspath in Compile).value.files,
        Array(slickDriver, jdbcDriver, url, outputDir, 
           targetPackageName, userName, password, "true", 
           "utils.CodeGenerator"
        ),
        streams.value.log)
    Seq(file(fname))
}
```
and the override (CustomizedCodeGenerator.scala) is then stripped down to simply:
```
package utils

import slick.codegen.SourceCodeGenerator
import slick.model.Model

class CodeGenerator(model: Model) extends SourceCodeGenerator(model) {
    override def Table = new Table(_) {
        override def EntityType = new EntityType {
            override def caseClassFinal = false
        }
    }
}
```
I have added the class string as last argument in the array to preserve backwards compatibility

**Comment by cvogt** [comment]
LGTM. Let's merge this when green, I or anyone. 

@mendrik Could you add simply a reference to this ticket to the docs? https://github.com/slick/slick/blob/master/doc/src/code-generation.md#customization Right after the link to the example project is fine. E.g. "Another, slightly briefer way is described in <this ticket>"

**Comment by mendrik** [comment]
Will do, but on vacation for another 2 weeks

**Pull request merged**
