### PR TITLE
Run codegenerator against all databases

### PR DESCRIPTION
**Pull request by trevorsibanda**
Improvement suggested in #1560

### CODE REVIEW

**Comment by cvogt** [comment]
@trevorsibanda I think we need more than this. This file: GenerateMainSources.scala runs SQL scripts against different databases and then uses the code generator to generate files from them. But not against all databases, only some of them.

**Comment by trevorsibanda** [comment]
@cvogt Updated it.

**Comment by cvogt** [comment]
Awesome stuff! Let's wait until  https://github.com/slick/slick/pull/1443 is through, so we can run this against all backends on CI. Oracle, DB2, SqlServer are currently not tested on our CI, but will be then.

**Comment by cvogt** [comment]
I see, looks like the tests actually don't pass for all dbs

**Comment by cvogt** [comment]
@trevorsibanda nice :)! See my slack messages.

**Comment by trevorsibanda** [comment]
@cvogt please have a look at this.

I added all dbms except Oracle and DB2. I opened #1746 and will work on adding both of these soon.

Hopefully we can get this merged to allow more tests on the codegen

**Comment by cvogt** [comment]
LGTM!

**Pull request merged**
