### PR TITLE
Adds insertOrUpdateAll

### LINKED ISSUE #1781: batch upsert performance
The current API doesn't appear to have support for batch upsert to allow for better performance when using upserts.
The following seems to work and gives performance of 100K rows in 3 seconds for a medium sized table against a local mysql 5.6 running in docker.  Would something along these lines be eligible for adding to api (it may be specific to rdbms which support batch upsert such as mysql):

```
object SlickBatch {
  def createBatchUpsert(compiled: MySQLProfile.JdbcCompiledInsert, values: Iterable[Any]): SimpleDBIO[Array[Int]] = {
    SimpleDBIO { context =>
      context.session.withPreparedStatement(compiled.upsert.sql) { (st: PreparedStatement) =>
        values.foreach { update =>
          st.clearParameters()
          compiled.upsert.converter.set(update, st)
          st.addBatch()
        }
        st.executeBatch()
      }
    }
  }
```

Application code:
```
  private lazy val tableQuery: TableQuery[B] = ???
  private lazy val tableQueryCompiled = MySQLProfile.compileInsert(tableQuery.toNode)
db.run(DBIO.seq(createBatchUpsert(tableQueryCompiled, updates)).transactionally) // note if not using "transactionally" need to turn autocommit off.
```
Configuration - include this database property:
```
database = {
  ....
  properties = {
    rewriteBatchedStatements = true
  }
}
```

### PR DESCRIPTION
**Pull request by jkugiya**
Added batch operation for `insertOrUpdate`. 

close #1781

### CODE REVIEW

**Comment by jkugiya** [comment]
Marked this PR draft, because we should consider naming strategy. (https://github.com/slick/slick/pull/2398)

**Comment by nafg** [comment]
I added a workflow to report mima results on the PR, closing & reopening to trigger

**Comment by nafg** [comment]
Hi, what's the status of this?

**Comment by nafg** [comment]
Please rebase

**Comment by nafg** [comment]
Thanks! So, what's the status? Is it ready to ship right after 3.4.0 (imminent)?

**Comment by jkugiya** [comment]
This PR works as intended, but I think we need to consider the name of the method. It should be consistent with `insert` so that users are not confused.

Proposed name in #2398 are as following.

- insertAll : multi-row insert
- insertAllBatch: batch insert. Same as existing ++=.
- insertOrUpdateAll: multi-row upsert
- insertOrUpdateBatch: batch upsert

The implementation of this PR is a batch upsert, but if #2398 is acceptable, then a multi-row upsert could also be implemented.

**Comment by lightbend-cla-validator** [comment]
Hi @jkugiya,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by lightbend-cla-validator** [comment]
Hi @jkugiya,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by nafg** [comment]
@jkugiya I want to tackle this now and merge it. Could we have a voice chat perhaps?

**Comment by jkugiya** [comment]
This PR is a follow-up to #2398

https://github.com/jkugiya/slick/pull/2

**Comment by nafg** [comment]
I just rebased this on #2398

**Comment by nafg** [comment]
Made some changes to simplify

**Comment by nafg** [comment]
@jkugiya #2398 was merged. This PR is rebased on `main`. Are you happy with it as is? If so please mark Ready for review.

**Comment by jkugiya** [comment]
@nafg Yes, I am happy!

**Pull request merged**
