### PR TITLE
Added new activator template.Which shows how to write a Slick applica…

### PR DESCRIPTION
**Pull request by satendrakumar**
…tion using the cake pattern, writing unit test and providing a seed for starting with Slick

### CODE REVIEW

**Comment by satendrakumar06** [comment]
@cvogt Please review this pull request i have updated content as you suggestion.

**Comment by satendrakumar06** [comment]
@cvogt Is this ok or something i need to change ?

**Comment by cvogt** [comment]
@szeiger What do you think?

**Comment by szeiger** [comment]
I haven't gotten around to looking at the actual template yet. However, we should not add it to the "Getting Started" list. Those are versioned templates that are considered to be part of the manual. Any new template would also have to be versioned and then maintained by us (i.e. by me), so the barrier to adding new templates is pretty high. The fewer of them we have, the better.

Just going by the description, it may be worthwhile to integrate the content of this new template into the slick-multidb tutorial. If it stays standalone and non-versioned, there is not necessarily anything more to do on our side because Activator already allows you to find all Slick-related templates. In addition to that we could feature a curated list of templates on the "Documentation" page of slick.typesafe.com.

**Comment by satendrakumar06** [comment]
Thanks @cvogt @szeiger

**Pull request closed without merging**
