### PR TITLE
use more descriptive val name in doc example

### PR DESCRIPTION
**Pull request by marko-asplund**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @marko-asplund,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by szeiger** [comment]
Looks like the changed version doesn't compile anymore

**Comment by hvesalai** [comment]
@marko-asplund can you update your PR so it compiles?

```
[error] /home/travis/build/slick/slick/slick/src/sphinx/code/GettingStartedOverview.scala:96: not found: value coffeeNames
[error]       coffeeNames
[error]       ^
[error] one error found
[error] (testkit/doctest:compile) Compilation failed
```

**Comment by hvesalai** [comment]
@marko-asplund the rebase alone is not enough, you changed the name of `coffeeNames`, but did not change all references.

**Comment by SethTisue** [comment]
closing for inactivity

**Pull request closed without merging**
