### PR TITLE
Use newer versions of sqlite and derby drivers

### PR DESCRIPTION
**Pull request by nafg**

### CODE REVIEW

**Comment by nafg** [comment]
slick-migration-api is failing on these so I want to see if the problem is with slick or not. Anyway better to use newer versions...

**Comment by nafg** [comment]
Slick seems broken with SQLite 3.15 (https://sqlite.org/releaselog/3_15_0.html)

**Comment by nafg** [comment]
And Derby _hangs_ it

**Comment by trevorsibanda** [comment]
The release log for Derby 10.12.1.1 notes some security changes which are responsible for failing tests. 

Solution seems to be configuring the security manager policy and granting additional permissions for the servers to boot up.
https://db.apache.org/derby/releases/release-10.12.1.1.cgi

Derby build error is
` java.security.AccessControlException: access denied org.apache.derby.security.SystemPermission( "engine", "usederbyinternals" ) `

Upgrading SQLite to latest version `sqlite-jdbc-3.20.0` doesn't seem to break unlike `sqlite-jdbc-3.19.3`

**Comment by hvesalai** [comment]
Is there going to be updates to this PR?

**Comment by hvesalai** [comment]
@nafg How about getting this done for 3.3?

**Comment by nafg** [comment]
Sorry I didn't get to this.

Are you or have you considered using scala-steward?

**Comment by WellingR** [comment]
@hvesalai I think this PR can be closed now that #2021 has been merged

**Pull request closed without merging**
