### PR TITLE
Uses db-configuration local numThreads and queueSize

### PR DESCRIPTION
**Pull request by taavi**
Should address https://github.com/slick/slick/issues/1139

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @taavi,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by szeiger** [comment]
Thanks, LGTM. I can't merge this without a signed CLA, however.

**Comment by taavi** [comment]
Working on it. :) Thanks!

**Comment by szeiger** [comment]
@taavi Any update here?

**Comment by taavi** [comment]
Actively waiting at my end.

**Comment by szeiger** [comment]
Thanks for the effort, but since this is a non-trivial bug, I decided to merge #1229 instead, so we can get the fix into 3.0.2 and 3.1.0-M2. I wouldn't want to delay this any longer. The situation would be different for a less critical issue or an improvement.

**Comment by taavi** [comment]
I understand. Thanks!

**Pull request closed without merging**
