### PR TITLE
[WIP] Test code coverage analysis

### PR DESCRIPTION
**Pull request by Sumith1896**
En route to fix https://github.com/slick/slick/issues/808

### CODE REVIEW

**Comment by Sumith1896** [comment]
Maybe move `scoverage.sbt` contents to `build.sbt`

**Comment by Sumith1896** [comment]
@cvogt @szeiger It's open for comments, though WIP.

**Comment by cvogt** [comment]
LGTM. Waiting for one more review. @szeiger or @d6y

**Comment by Sumith1896** [comment]
Now working locally:
Try it out by
`sbt clean coverage test`
then 
```
sbt coverageReport
sbt coverageAggregate
```
The XML/HTML report will be available here `./slick/target/scala-2.11/`

I'll look in into how to integrate this into some web service online.

**Comment by cvogt** [comment]
@Sumith1896 doesn't look like M2 can be found

**Comment by Sumith1896** [comment]
Weird. Works locally for me. Any idea about the idea?

**Comment by cvogt** [comment]
maybe you have a resolver in your local sbt config, that slick doesn't have?  Also, is it possible not to use a milestone release? Eventhough I realize it's non-critical for code coverage

**Comment by d6y** [comment]
I applied this patch to my local copy of slick and had the same resolver issues that Travis reports.

To get it running I had to:
- remove _project/scoverage.sbt_ - doesn't seem to do anything for me. 
- update coverals in _build.sbt_ to be `addSbtPlugin("org.scoverage" % "sbt-coveralls" % "1.1.0")`
- adjust the root _scoverage.sbt_ for the changes in 1.1.0

My _scoverage_ file now looks like this:

```scala
import org.scoverage.coveralls.Imports.CoverallsKeys._

coverageHighlighting := true

coverallsToken := sys.props.get("coveralls-repo-token")
```

Not 100% sure about the `coverallsToken` part, as I have no token

With those changes in place, running [the commands posted](https://github.com/slick/slick/pull/1433#issuecomment-182248868) by @Sumith1896  does indeed give me a local coverage report:

scoverage code coverage 2016-03-02 17-52-55

@Sumith1896 - does the above help you revisit this PR, so we can progress it a bit more?

**Comment by Sumith1896** [comment]
Thanks @d6y. I'll update this.

**Comment by Sumith1896** [comment]
I've updated the PR as per @d6y comments

**Comment by Sumith1896** [comment]
Coveralls down for maintenance https://twitter.com/CoverallsApp/status/707506220274360321

**Comment by d6y** [comment]
What can we do to re-run the checks?  Touch a file or something?

**Comment by smootoo** [comment]
There will be a rebuild button on the circleci and travis builds if you are logged in and a member of the group owning the builds in github. I think that's these people for now https://github.com/orgs/slick/people.

**Comment by d6y** [comment]
Thanks @smootoo.  

@szeiger can you please press the rebuild button as Coveralls was down when this PR was last attempted.

Thank you

**Comment by d6y** [comment]
@Sumith1896 I'm re-running the build checks...

**Comment by hvesalai** [comment]
What is the future of this PR? Will it get fixed? ping @Sumith1896 @d6y @smootoo

**Comment by SethTisue** [comment]
closing for inactivity

**Pull request closed without merging**
