### PR TITLE
Tmp/developer docs

### PR DESCRIPTION
**Pull request by cvogt**
review by @szeiger @dvinokurov

### CODE REVIEW

**Comment by d6y** [comment]
This is important information to have access to for new contributors.

I guess this kind of information may changes per-major version, so having it as a new section in the manual makes sense.  Arguably it could be in the [README](https://github.com/slick/slick/blob/master/README.md) or should be linked to from the README.

There's also bits in [the wiki](https://github.com/slick/slick/wiki/Release-steps) that could migrate into the manual too.

So perhaps:

slick slick 3 1 1 documentation 2016-03-03 09-07-13

...at least some minimal information for now, and grow it over time.

**Comment by smootoo** [comment]
Agree that this is useful to have. Now I've started working in the Slick codebase, there is stuff I could add in here (e.g. getting a working dev cycle with intellij, using docker instances for testing standalone dbs)

**Comment by cvogt** [comment]
+1 ! Somebody wanna take this? @Sumith1896 :) ?

**Comment by Sumith1896** [comment]
Will do this. Thanks @cvogt

**Comment by cvogt** [comment]
Hej, thank YOU, man :)

**Comment by Sumith1896** [comment]
@cvogt I opened a fresh PR here https://github.com/slick/slick/pull/1458. You can pour in your suggestions there. This can be closed.
@d6y Could you have a look too? Let me know what I need to add.
@smootoo Awesome, you can send in a PR to my branch or you could add once https://github.com/slick/slick/pull/1458 is merged :)

**Comment by d6y** [comment]
Closing, as requested by @Sumith1896 --- the work has moved to #1458

**Pull request closed without merging**
