### PR TITLE
Add multiple files (one per table) code generation #906

### PR DESCRIPTION
**Pull request by olivergg**
TODO : write a proper (and relevant) junit test.

### CODE REVIEW

**Comment by olivergg** [comment]
I've just updated the branch to rebase from upstream. Since it has been over a year now, I'm back to square one.

```
project testkit
testOnly scala.slick.test.codegen.GeneratedCodeTest
```
still generates the following files in `slick/target/slick-testkit-codegen-tests/all/test` :  
```
├── DerbyDriver.scala
├── H2Driver.scala
├── HsqldbDriver.scala
├── multiple
│   ├── CategoriesTable.scala
│   ├── DerbyDriverTables.scala
│   ├── H2DriverTables.scala
│   ├── HsqldbDriverTables.scala
│   ├── PostsTable.scala
│   └── SQLiteDriverTables.scala
└── SQLiteDriver.scala
```

But nothing is generated in `slick/slick-testkit/target/scala-2.10/src_managed/test/slick-codegen/slick/test/codegen` which still contains the following : 
```
.
├── generated
│   ├── AllTests.scala
│   ├── CG10.scala
│   ├── CG1.scala
│   ├── CG2.scala
│   ├── CG3.scala
│   ├── CG7.scala
│   ├── CG8.scala
│   └── CG9.scala
├── roundtrip
│   └── Tables.scala
└── roundtrip2
    └── Tables.scala
```

So I can't modify `slick/slick-testkit/src/test/scala/slick/test/codegen/GeneratedCodeTest.scala` to add a unit test that uses the files in `multiple`.

What's the proper way to do that ?

Thanks

**Comment by stewSquared** [comment]
@olivergg @cvogt What's the status here? Did the PR look fine before the merge conflicts?
I'm interested in this feature and willing to complete this work if necessary.

**Comment by olivergg** [comment]
@stewSquared Thanks for your interest in this PR. It's been quite a while now, so I don't know if the codegen API has changed (but it's most likely). I guess a working unit test **that compiles** would be the first thing to do...

**Comment by hvesalai** [comment]
Continued in #1785

**Pull request closed without merging**
