### PR TITLE
Travis-CI: simplify config, drop broken JDK 15

### PR DESCRIPTION
**Pull request by SethTisue**
by borrowing from scala-dev

we use this in many scala/* repos and are happy with it

### CODE REVIEW

**Comment by SethTisue** [comment]
puzzled why this is failing. I'll have to take a closer look when I have more time

**Comment by nafg** [comment]
On my machine,

```text
$ sdk list java | grep -o ' ..\.[0-9\.]*hs-adpt'
 16.0.0.hs-adpt
 13.0.2.hs-adpt
 11.0.10.hs-adpt
 11.0.9.hs-adpt
 11.0.6.hs-adpt
 11.0.4.hs-adpt
 11.0.3.hs-adpt
```

there is no 15

So the script doesn't work for arbitrary versions

**Comment by nafg** [comment]
Hmm, this doesn't actually break anything, it brings an issue to the fore.

See for instance the output of https://travis-ci.com/github/slick/slick/jobs/494699712. It's for ADOPTOPENJDK=15, but in actuality it seems to be using 11.

**Comment by nafg** [comment]
What do other projects using the scala-dev file do? Is there something other than sdkman we can use? (Such as Jabba, jenv, or Coursier)

Maybe this is moot once we switch to github actions.

**Comment by SethTisue** [comment]
@nafg ah nice, thanks for spotting that!

I've added a commit that just drops 15 from the matrix. so I believe that makes this PR mergeable.

I'm surprised to learn that SDKMAN doesn't offer 15 anymore, but in this repo, I don't think we care, it does offer 16 and we can try move forward with that in #2199

**Pull request merged**
