### PR TITLE
Test on JDK 21 instead of 17 and fix 

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Review by nafg — APPROVED** [review]

**Comment by nafg** [comment]
Thanks!

**Comment by nafg** [comment]
Uh oh @xuwei-k that other pr is causing this to fail, can you figure out why?

**Review by nafg — APPROVED** [review]
Thanks!

**Review by nafg — CHANGES_REQUESTED** [review]
Can you update .mergify.yml too?

**Comment by xuwei-k** [comment]
> Can you update .mergify.yml too?

done

**Review by nafg — APPROVED** [review]
Thanks!

**Pull request merged**
