### PR TITLE
added RawDefault ColumnType to map to RAW sql

### PR DESCRIPTION
**Pull request by prakhunov**
I tried looking for an issue in assembla but I'm not even sure if you guys consider it an issue.

I am currently writing an app that uses slick and a lot of the primary id's are UUIDs and the DefaultValue option for me is practically useless. 

I would like UUID's to be generated on the Database (newsequentialid() (SQL Server) or uuid_generate_v1 (postgres) )  this way the indexes won't get too crazy.

Sadly you will not get any compile time checking for default values however this change would make it easier to point to default database functions.

I have also signed the CLA .

### CODE REVIEW

**Comment by hvesalai** [comment]
Is this in any form applicable to 3.2? If not, I would like to close it.

**Comment by hvesalai** [comment]
Tentatively scheduled this for 3.3. in the hopes that @brianchizhang would revive it as suggested in #1146.

**Comment by brianchizhang** [comment]
Inability to support default values for updated timestamp and created timestamp is the only thing holding us back from utilizing CodeGen for production environment, this would be a much appreciated feature.

**Comment by hvesalai** [comment]
@brianchizhang what I meant was that if you update this, then we can include it. There is nobody else to do it.

**Comment by hvesalai** [comment]
As nobody is working on this, I'm de-scheduling it from 3.3 to an indefinite time in the future.

**Comment by SethTisue** [comment]
closing for inactivity

**Pull request closed without merging**
