### PR TITLE
MySQLProfile: quote column names in `insertOrUpdate` statement

### LINKED ISSUE #2910: Slick 3.5.0, MariaDB, `insertOrUpdate` fails with `You have an error in your SQL syntax`
**MariaDB**: 10.6.11
**Slick**: 3.5.0
**Scala version**: 2.13.13

**DESCRIPTION:**

`insertOrUpdate` fails after upgrading to Slick `3.5.0`.

**STEPS TO REPRODUCE:**

The script:
```scala
//> using scala 2.13.13
//> using dep "com.typesafe.slick::slick:3.5.0"
//> using dep "org.mariadb.jdbc:mariadb-java-client:3.3.3"

import slick.jdbc.MySQLProfile.api._
import scala.concurrent.Await
import scala.concurrent.duration._

object SlickExample {

  class Settings(tag: Tag) extends Table[(String, String)](tag, "settings") {
    def key = column[String]("key", O.PrimaryKey)
    def value = column[String]("value")
    def * = (key, value)
  }

  object SettingsTable extends TableQuery(new Settings(_)) {}

  def main(args: Array[String]): Unit = {
    val db = Database.forURL(
      url = "jdbc:mariadb://localhost:3306/test",
      user = "root",
      password = "root",
      driver = "org.mariadb.jdbc.Driver"
    )

    val query = SettingsTable.insertOrUpdate(("key_1", "value_1"))

    Await.result(db.run(query), 10.seconds)
  }
}
```

~~The prepared statement is identical for `3.4.1` and `3.5.0`:~~

The prepared statements are different.

**3.4.1**:
```sql
insert into `settings` (`key`,`value`)  values (?,?) on duplicate key update `key`=VALUES(`key`), `value`=VALUES(`value`)
```

**3.5.0**:
```sql
insert into `settings` (`key`,`value`)  values (?,?) on duplicate key update key=VALUES(key), value=VALUES(value)
```

**ACTUAL RESULT:**

The script fails with the following error:
```
Exception in thread "main" java.sql.SQLSyntaxErrorException: (conn=127) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'key=VALUES(key), value=VALUES(value)' at line 1
        at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:289)
        at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:378)
        at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:172)
        at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:913)
        at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:852)
        at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:771)
        at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:695)
        at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:93)
        at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:342)
        at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:319)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.$anonfun$nativeUpsert$1(JdbcActionComponent.scala:674)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:570)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.nativeUpsert(JdbcActionComponent.scala:671)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.f$1(JdbcActionComponent.scala:654)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.run(JdbcActionComponent.scala:667)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:32)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:29)
        at slick.basic.BasicBackend$BasicDatabaseDef.liftedTree1$1(BasicBackend.scala:323)
        at slick.basic.BasicBackend$BasicDatabaseDef.$anonfun$runSynchronousDatabaseAction$2(BasicBackend.scala:323)
        at slick.basic.BasicBackend$BasicDatabaseDef.$anonfun$runSynchronousDatabaseAction$2$adapted(BasicBackend.scala:318)
        at slick.util.AsyncExecutor$$anon$1$$anon$2.runAndCleanUp(AsyncExecutor.scala:187)
        at slick.util.AsyncExecutor$$anon$1$$anon$2.run(AsyncExecutor.scala:198)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Once I roll back to `3.4.1`, the script works without errors.

**EXPECTED RESULT:**

The `insertOrUpdate` works.

**SETUP:**

MariaDB in docker:
```yml
version: '3'
services:

  db:
    image: 'mariadb:10.6.11'
    ports:
      - '3306:3306'
    command: '--sql_mode="" --log-bin'
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
```

### PR DESCRIPTION
**Pull request by iRevive**
Closes #2910.

It would be nice to write a test for this functionality. I'm unfamiliar with Slick's codebase, so where is the best place to add a test?

### CODE REVIEW

**Comment by nafg** [comment]
@mdedetrich any idea why MiMa is reporting these incompatibilities? https://github.com/slick/slick/pull/2912#issuecomment-1987418910

**Comment by jkugiya** [comment]
https://github.com/iRevive/slick/pull/1

@nafg @iRevive 
Sorry for the inconvenience. I have fixed it so that the test fails in the original implementation in the buggy case, so you can take it in if you like.

**Comment by jkugiya** [comment]
@nafg 

> @mdedetrich any idea why MiMa is reporting these incompatibilities? https://github.com/slick/slick/pull/2912#issuecomment-1987418910


I don't know why, but the same report was output when I output the report after publishLocal of the main branch. I think it is a plugin issue.

```
$ sbt shell
sbt:slick-root> clean
sbt:slick-root> publishLocal
sbt:slick-root> set every CompatReportPlugin.previousRelease := Some("3.5.0")
sbt:slick-root> writeCompatReportToGitHubOutput
```

**Comment by mdedetrich** [comment]
> @mdedetrich any idea why MiMa is reporting these incompatibilities? [#2912 (comment)](https://github.com/slick/slick/pull/2912#issuecomment-1987418910)

I am guessing that since the inliner is enabled in CI its actually doing the work its meant to and inlining the classes and I forgot to add these cases to MiMa when creating the original PR.

Ill make a PR to solve this

**Comment by nafg** [comment]
@Mergifyio rebase

**Review by nafg — APPROVED** [review]

**Pull request merged**
