### PR TITLE
Build the different scala versions separately in travis

### PR DESCRIPTION
**Pull request by WellingR**
As I was investigating if slick could be upgraded to scala 2.13, it turned out that building 3 scala versions in sequence caused the travis build to take too long.

This change significantly reduces the build time.

One thing that should be carefully reviewed is what the consequences are on the release process. (as I do not know how the slick release process works I am not able to test this)

### CODE REVIEW

**Comment by hvesalai** [comment]
```
[error] Failed: Total 1744, Failed 1, Errors 0, Passed 1743
[error] Failed tests:
[error] 	slick.test.codegen.GeneratedCodeTest
[error] (testkit/test:test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by WellingR** [comment]
This seemed to be a spurious db2 test failure which occurs if a schema is dropped before the SYSTOOLSPACE tablespace has been created.
The same problem occurred when I tried to run these tests locally.

According to https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.admin.gui.doc/doc/c0023713.html the `db2look` command also creates this table space. Hopefully these failures no longer occur

**Comment by WellingR** [comment]
The latest change seems to have resolved the issue. I not check if the tablespace exists, and create it if it did not yet exist.

**Comment by hvesalai** [comment]
Let's merge this to master and then worry about release later

**Pull request merged**
