### PR TITLE
assorted upgrades

### PR DESCRIPTION
**Pull request by SethTisue**
this overlaps somewhat with #2106 and #2123. but it seems worthwhile to me to land these easy upgrades first. (the more ambitious PRs seem to have stalled.)

### CODE REVIEW

**Comment by SethTisue** [comment]
niiiiice, Travis-CI likes it. anybody out there who could merge it?

**Comment by SethTisue** [comment]
@marcospereira can I interest you in merging this? and/or in giving me merge rights here?

**Review by marcospereira — APPROVED** [review]

**Comment by marcospereira** [comment]
> @marcospereira can I interest you in merging this? and/or in giving me merge rights here?

I don't have the right to give you merge rights. I see @edwardcallahan and @jboner are both owners here, so maybe they can do that.

**Comment by SethTisue** [comment]
I have admin rights now thanks to @edwardcallahan 

tumblr_mquu3nelwb1s46h7vo1_500

**Pull request merged**
