### PR TITLE
Fixing part 1 of #1408 by unrolling tail end flatmaps

### PR DESCRIPTION
**Pull request by deusaquilus**
Taking all flatmaps in the tail position of a clause and unrolling them into a chained Bind node in the AST.

### CODE REVIEW

**Comment by cvogt** [comment]
This is great. LGTM. @szeiger ?

**Comment by deusaquilus** [comment]
Please note that this fix is not recursive, if there are additional .map steps appended at the end of the .flatMap the logic will not kick in and the error case will once again occur. Please let me know if this limitation is acceptable, otherwise more complex logic is needed.

**Comment by typesafehub-validator** [comment]
Hi @deusaquilus,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by deusaquilus** [comment]
Okay, I tried to handle the transitivity and add additional test cases.

**Comment by deusaquilus** [comment]
Not sure why CLA validator does not work. Going to try to push again.

**Comment by deusaquilus** [comment]
Please refer to #1674 which is an updated PR.

**Pull request closed without merging**
