### PR TITLE
Add test for join containing group by and filter

### PR DESCRIPTION
**Pull request by sebigavril**
It seems that joining a table and a subselect containing a `groupBy` and a `filter` generates an incorrect sql statement. This is the sql generated for the code in this PR:

``` sql
SELECT x2."city" 
FROM   (SELECT "supplier_id" AS x3, 
               Min("price")  AS x4 
        FROM   "coffee" 
        GROUP  BY "supplier_id") x5, 
       "supplier" x2 
WHERE  ( x5.x4 < 100 ) 
       AND ( x2."id" = x5.x6 ) 
```

**Column `x5.x6` is not declared as an alias anywhere**

For more complex tables I couldn't even get the sql to generate column aliases for table `x5`

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @sebigavril,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by cvogt** [comment]
thank you. test cases like this are great!

**Comment by sebigavril** [comment]
@cvogt do I also need to create an issue, or is this PR enough?

**Comment by cvogt** [comment]
PR is enough

**Comment by timgautier** [comment]
I was just about to issue a pull request to demonstrate the same bug. Rather than be totally redundant, I'll just add my query here. This was at the end of the AggregateTest.testGroupBy method.

      val q = ts
        .groupBy(_.a)
        .map { case (a, ts) => (a, ts.map(_.b).max) }
        .filter(_._2 > 3)
      val outer = ts
        .filter(_.a === 2)
        .join(q).on(_.a === _._1)
        .map(_._2)
        .distinct
      db.run(mark("q14", outer.result)).map { rt =>
        rt shouldBe Vector((2, Some(5)))

If you remove `.filter(_._2 > 3)` the test passes.

**Comment by SethTisue** [comment]
closing for inactivity

**Pull request closed without merging**
