### PR TITLE
Escape Special Characters in AbstractSourceCodeGenerator.scala

### PR DESCRIPTION
**Pull request by trevorsibanda**
#1250

### CODE REVIEW

**Comment by cvogt** [comment]
@trevorsibanda a test demonstrating that this was actually broken and that this is the fix would be great. Probably adding a field here would do it: https://github.com/slick/slick/blob/master/slick-testkit/src/codegen/scala/slick/test/codegen/GenerateRoundtripSources.scala

**Comment by cvogt** [comment]
@trevorsibanda any update on this?

**Comment by trevorsibanda** [comment]
Yep, I wrote tests, I tried recovering to my fork after deleting my repo thats why I couldnt continue submitting commits on this. I will open a new PR

**Comment by trevorsibanda** [comment]
Deleted original repository.

Reopened PR in #1632 and added test

**Pull request closed without merging**
