### PR TITLE
Fixed spelling error

### PR DESCRIPTION
**Pull request by paul-porter**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @paul-porter,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by Sumith1896** [comment]
+1. Could you sign the CLA?

**Comment by paul-porter** [comment]
done

**Comment by cvogt** [comment]
thx guys :)

**Pull request merged**
