### PR TITLE
Travis-CI: test on JDK 16

### PR DESCRIPTION
**Pull request by SethTisue**
now that 16 is GA

### CODE REVIEW

**Comment by SethTisue** [comment]
```
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:172)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:238)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:434)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:316)
	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188)
	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:99)
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:352)
	... 22 more
```

anybody know what this is about or what we should do about it?

**Comment by nafg** [comment]
Turns out builds were previously using jdk 11 in fact, not 15 as they were supposed to. So this could have broken on any jdk 12+.

**Comment by SethTisue** [comment]
I don't intend to investigate this myself. Somebody else want to look into it...?

**Comment by SethTisue** [comment]
Replacing this with a help-wanted issue, since I won't be pursuing it further myself: https://github.com/slick/slick/issues/2212

**Pull request closed without merging**
