### PR TITLE
Add cookbook entry for tracking number of query compilations

### PR DESCRIPTION
**Pull request by alexklibisz**
~~This also includes some fixed typos and links in contributing.md~~

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Review by adkafka — APPROVED** [review]

**Comment by nafg** [comment]
About CONTRIBUTING.md, I guess Typesafe should change to Lightbend.

@SethTisue otherwise is the file still correct?

**Comment by nafg** [comment]
Also separate PRs would be nicer but it doesn't really matter if you don't feel like it

**Review by nafg — APPROVED** [review]

**Comment by SethTisue** [comment]
The CONTRIBUTING.md changes LGTM. Agree that a separate commit for that would be a little better.

The Typesafe->Lightbend change would be nice, but I'm not concerned about it. In a funny way, leaving it "Typesafe" communicates that this is old information that may or may not be up to date.

**Comment by SethTisue** [comment]
If it's unclear why the CLA validator is complaining, let us know and we'll explain.

**Comment by alexklibisz** [comment]
Thanks for the quick replies. 

> If it's unclear why the CLA validator is complaining, let us know and we'll explain.

Yeah, I'm a little confused here. It might be because I only authorized my company email w/ my github acct _after_ making the first commit? My understanding is that we have a signed CLA on record with Lightbend.

> Also separate PRs would be nicer but it doesn't really matter if you don't feel like it

I can pull that change out onto its own PR. Maybe that'll fix the CLA issue.

**Comment by lightbend-cla-validator** [comment]
Hi @alexklibisz,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by nafg — APPROVED** [review]

**Comment by nafg** [comment]
@alexklibisz this is still waiting for your signature

**Comment by alexklibisz** [comment]
image


@nafg Can you re-run the check?

I basically stumbled through the checks starting with the typsafe-cla-validator Details link. Other than that, I'm not really sure what else to do.

**Comment by nafg** [comment]
Seems closing & reopening helps (h/t @SethTisue)

**Pull request merged**
