### PR TITLE
upgrade to latest scala-collection-compat

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Comment by jczuchnowski** [comment]
The latest version is 2.1.4 now.

**Comment by SethTisue** [comment]
I'd be happy to merge this if it passes CI after rebase.

**Comment by SethTisue** [comment]
rebased in the hopes that a build on travis-ci.com (as opposed to travis-ci.org) would trigger

**Comment by SethTisue** [comment]
gah... well, I'm going to merge it anyway, but not until after #2106 lands

**Comment by SethTisue** [comment]
well, I'm going to have to sort out the Travis-CI situation, but...

**Pull request merged**
