### PR TITLE
Tag-based publishing to Sonatype

### PR DESCRIPTION
**Pull request by szeiger**
Testing by staging a 3.2.1-TEST1 release. Release and `v3.2.1-TEST1` tag will be deleted.

### CODE REVIEW

**Comment by szeiger** [comment]
The build is just a tiny bit too slow and gets aborted: https://travis-ci.org/slick/slick/builds/228309945

The artifacts on Sonatype look complete but closing failed because 2 signatures couldn't be verified, so either the signature files must be missing or the artifacts weren't uploaded entirely. In any case it seems to be a matter of mere seconds.

**Comment by szeiger** [comment]
Copy&paste error in the build script caused everything to build twice: https://github.com/slick/slick/blob/cdf3693ee873e2ce14cd6ba0fbf6907148c14298/admin/build.sh#L23-L25 - Trying again with a single build...

**Comment by szeiger** [comment]
Successful run (took 34min): https://travis-ci.org/slick/slick/builds/228340566, all artifacts cross-published for 2.11 and 2.12 with the correct version number to https://oss.sonatype.org/content/repositories/comtypesafe-1825/, repository closed successfully.

I have already deleted the `v3.2.1-TEST1` tag from github. The staging repository is closed but not dropped, so you can still inspect it for review.

**Comment by cvogt** [comment]
LGTM!

**Pull request merged**
