### PR TITLE
#1340 distinct on

### PR DESCRIPTION
**Pull request by shmishleniy**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @shmishleniy,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by hvesalai** [comment]
Thank you for the PR. It looks good to me, let's give others a chance to review also.

**Comment by CarpathianUA** [comment]
Hey guys,
Any news when the PR can be merged?

**Review by renatocaval — APPROVED** [review]

**Comment by renatocaval** [comment]
Thanks @shmishleniy 

@CarpathianUA, I'm planning to backport this fix to 3.3.x branch. The goal is to include it on the upcoming 3.3.3 release.

**Comment by shmishleniy** [comment]
@renatocaval here is the fix for 3.3.x branch as well
https://github.com/shmishleniy/slick/commits/1340_distinct_on

**Pull request merged**
