### PR TITLE
Use Enumeration type in custom-scalar-types-example

### PR DESCRIPTION
**Pull request by arve0**
Solves issue #2028

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @arve0,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by WellingR** [comment]
This is simply a workaround which has the that #2028 does not occur. But it does not resolve #2028.

Having said that, I would be okay with merging this as this example is easier to work with as long as #2028 is not yet solved.

**Comment by arve0** [comment]
@wellingr For my enlightenment, can you give a pointer of how it should be fixed proper? To me, “does not occur” is equivalent to solving the issue, so would be glad to learn how the issue have more nuances to it.

**Comment by hvesalai** [comment]
Can you rebase on newest master. There was a configuration problem in master that has now been fixed.

**Pull request merged**
