### PR TITLE
Update orm-to-slick.md

### PR DESCRIPTION
**Pull request by torkelrogstad**
Fixes typo in link to `sql.md`.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @torkelrogstad,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by d6y** [comment]
@hvesalai does this need to go direct to master, or is 3.2.x branch still in play?

**Comment by hvesalai** [comment]
I accidentally now merged this into 3.2. We need this also for 3.3. Anybody up for it?

**Comment by hvesalai** [comment]
I cherry-picked it. So it's now done!

**Comment by renatocaval** [comment]
Seems that the CLA is not fully functional. 

Signing was done here: https://www.lightbend.com/contribute/cla/check/torkelrogstad

**Pull request merged**
