### PR TITLE
Add limited tuple inSet support

### PR DESCRIPTION
**Pull request by cvogt**
This is a partial fix for #517

### CODE REVIEW

**Comment by devisaneer** [comment]
@cvogt I'm keen to your pull request this merged into 2.1.x or 3.x. [FYI: Thank you for posting the workaround tip, I found it helpful today!] :+1:

**Comment by cvogt** [comment]
@szeiger WDYT?

**Comment by djx314** [comment]
Any news for this? It's a good function.

**Comment by kheraud** [comment]
For this issue, are we talking about "Where in" for multi columns (http://stackoverflow.com/questions/435418/where-in-with-multiple-columns-sql-server) or about adding a ColumnExtensionMethods to handle inSet for tuples : inSet[R](seq: Product[B1]) ?

**Comment by cvogt** [comment]
@szeiger opinions?

**Comment by Fristi** [comment]
This would be very useful, to bad to see it stale

Use case for me:

```scala
final case class ShowId(id: Int)
final case class EpisodePointer(showId: ShowId, season: Int, episodeNr: Int)

def currentEpisodes(episodePointers: Seq[EpisodePointer])(implicit EC: ExecutionContext): Future[Seq[Episode]] =
  db.run(episodes.filter(x => x.pointer inSet episodePointers).result)
```

`EpisodePointer` can be translated to a tuple form, not sure if that's included in this PR.

**Comment by SethTisue** [comment]
closing for inactivity

**Comment by kenwang-coursera** [comment]
> In any case, here is the workaround which you can easily employ by hand:
> 
> ```
> someQuery.filter(p =>
>   someSet.map{
>     case(_1, _2, ...) =>
>       _1 === p.col_1 && _2 === p.col_2 && ...
>   }.reduce(_ || _)
> )
> ```

Can someone tell me why this would be preferred over something that seems a lot more straightforward such as:

```
someQuery.filter(p =>
  someSet.contains {
    case(_1, _2, ...) =>
      _1 === p.col_1 && _2 === p.col_2 && ...
  }
)
```

**Pull request closed without merging**
