### PR TITLE
Fix broken link in getting started documentation.

### PR DESCRIPTION
**Pull request by takashima0411**
Now regex is 
`"v3.3.1-SNAPSHOT".replaceFirst("""(\d*.\d*).*""", """$1""")` -> `v3.3`
but, expected result is `v3.3.1`.
Fixed version is
`"v3.3.1-SNAPSHOT".replaceFirst("""(\d?\.\d?\.\d?).*""", """$1""")` -> `v3.3.1`
and
`"v3.3.1-SNAPSHOT".replaceFirst("""(\d?\.\d?\.\d?).*""", "$1")` -> `v30.13.12`

Should I use `v3.3.1` or `3.3.x`?
https://github.com/slick/slick/issues/2093

But, zip url broken yet.

### CODE REVIEW

**Comment by renatocaval** [comment]
> Should I use v3.3.1 or 3.3.x?

It should be 3.3.x. The 'v' is used for the tag in git, but the branch is 3.3.x.

**Review by renatocaval — DISMISSED** [review]

**Comment by takashima0411** [comment]
regex fixed below.

|sample | acutual                    |
|--------|------------------|
|3.3.1-SNAPSHOT       | 3.3.x|
|3.3.1                              | 3.3.x|
|10.10.10-SNAPSHOT |10.10.x|
|10.10.10                         |10.10.x|

**Comment by SethTisue** [comment]
"Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting."

I'll inquire within Lightbend whether we can get the Slick org added to our paid Travis-CI plan.

**Comment by SethTisue** [comment]
thank you!

**Pull request merged**
