### PR TITLE
Support batch updates, if it's supported by db

### PR DESCRIPTION
**Pull request by SethTisue**
resubmission of #2056 

original PR description:

> Looks like `useBatchUpdates` on the `ReturningInsertActionComposerImpl` was hardcoded to false which did not allow batch updates to work if the database supported it.

> This would fix the issue and let us do batch inserts with returning ids on a database that supports it (MariaDB in our case)

### CODE REVIEW

**Comment by smrutimo** [comment]
@SethTisue Thanks!

**Comment by SethTisue** [comment]
CI likes it. Anyone feel able to review this...?

**Comment by tarsa** [comment]
I see at least two problems:
1) no tests
2) hardcoding to true is also too extreme. we probably should check whether the returned values are IDs, because otherwise query would fail (and that also needs a test)

Fortunately there's already an unused method
```scala
    protected def checkInsertOrUpdateKeys: Unit =
      if(keyReturnOther) throw new SlickException("Only a single AutoInc column may be returned from an insertOrUpdate call")
```
We could do similar check in `def useBatchUpdates`, i.e. make this:
```scala
override protected def useBatchUpdates(implicit session: Backend#Session) = !keyReturnOther
```

Also, instead of overriding a method in MySqlProfile, there should be an additional capability in slick.jdbc.JdbcCapabilities ? Then the decision could be done in slick.jdbc.JdbcActionComponent.ReturningInsertActionComposerImpl#useBatchUpdates :
```scala
    override protected def useBatchUpdates(implicit session: Backend#Session) =
      capabilities.contains(JdbcCapabilities.returnInsertKeyBatch) && !keyReturnOther
```

**Comment by nafg** [comment]
Should we have a label "needs tests"?

Actually, do we have code coverage, and if yes can we see if this path is already covered by tests (although I'm not sure if that would guarantee the return value is handled correctly)?

**Comment by SethTisue** [comment]
> do we have code coverage

We don't, and it's not clear it would make sense to add it unless/until https://github.com/scoverage/sbt-scoverage/issues/319 is resolved

**Comment by tarsa** [comment]
There's a test for inserts that return values instead of just counts: https://github.com/slick/slick/blob/fd0fd1e30ac59e79dfc584757bea0b95329bf308/slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/InsertTest.scala#L84-L112

There's just one action that does batch insert while returning some data per row, but it returns single column only:
```scala
    def ins1 = as.map(a => (a.s1, a.s2)) returning as.map(_.id)
...
      _ <- (ins1 ++= Seq(("e", "f"), ("g", "h"))) map (_ shouldBe Seq(3, 4))
```
There should be some test that does batch insert (i.e. > 1 row added at once, using ++= instead of +=) while returning more than one column (because AFAIU that is supported right now by automatically breaking batch into separate queries). There's already a query that returns more than one column:
```scala
    def ins2 = as.map(a => (a.s1, a.s2)) returning as.map(a => (a.id, a.s1))
```
Looking at how it's tested:
```scala
      _ <- ifCap(jcap.returnInsertOther) {
        (ins2 += ("c", "d")) map { id2: (Int, String) => id2 shouldBe (2, "c") }
      }
      _ <- ifNotCap(jcap.returnInsertOther) {
        (ins1 += ("c", "d")) map { id2: Int => id2 shouldBe 2 }
      }
```
there should be probably something similar applied to:
```scala
      _ <- (ins1 ++= Seq(("e", "f"), ("g", "h"))) map (_ shouldBe Seq(3, 4))
```
like maybe:
```scala
      _ <- ifCap(jcap.returnInsertOther) {
        (ins2 ++= Seq(("e", "f"), ("g", "h"))) map { _ shouldBe Seq((3, "e"), (4, "g")) }
      }
      _ <- ifNotCap(jcap.returnInsertOther) {
        (ins1 ++= Seq(("e", "f"), ("g", "h"))) map (_ shouldBe Seq(3, 4))
      } 
```
?

**Comment by nafg** [comment]
Ok, is anyone going to write those tests? @smrutimo can you?

**Comment by smrutimo** [comment]
> Ok, is anyone going to write those tests? @smrutimo can you?

Will do. When I get back from vacation

**Comment by nafg** [comment]
Thanks! I've assigned the issue to you, to keep track of that.

**Comment by SethTisue** [comment]
closed/reopened to reset CI

**Comment by SethTisue** [comment]
closed/reopened to reset CI

**Comment by nafg** [comment]
@smrutimo hi, what's the status of this?

**Comment by smrutimo** [comment]
> @smrutimo hi, what's the status of this?

@nafg I am so sorry! Completely forgot about this one as I switched jobs and don't work with slick/MySQL anymore. Let me see if I can turn this around in the next week or so.

**Comment by SethTisue** [comment]
rebased

**Comment by SethTisue** [comment]
> > do we have code coverage
> We don't

we do now: #2233

**Comment by nafg** [comment]
Wait, why was the `session.capabilities.supportsBatchUpdates` implementation reverted? All databases never support returning insert actions for batch updates, but MySQL always does?

What is the scope of the capability bit?

**Comment by nafg** [comment]
(This PR should be squashed when it's merged.)

**Comment by nafg** [comment]
And does it need tests or was the conclusion that it doesn't?

**Comment by reibitto** [comment]
I was looking into why inserts weren't being batched in my project and landed on that same line. I changed that `false` locally to `session.capabilities.supportsBatchUpdates` and that did it. Returning insert actions works fine with Postgres at least (not just MySQL). But as long as `session.capabilities.supportsBatchUpdates` is being used, then I don't think it's a problem as that's delegating to the driver anyway.

**Comment by reibitto** [comment]
Oh, but I guess there might be a situation where `boolean supportsBatchUpdates()` return true but somehow doesn't play well with `returning`? I guess that's why it was set to `false` in the first place? But like I said, it seems to work fine with Postgres so far.

**Comment by nafg** [comment]
@smrutimo can you respond to my comments?

**Comment by SethTisue** [comment]
@smrutimo ping

**Comment by smrutimo** [comment]
@SethTisue Thanks for the ping! sorry I had other priorities. But picked this one up last night and had to go through a bunch of recollection to figure out why I did this. 

@nafg @reibitto The real problem was that the inserts were not using batches and hence was not performing like it should. Now, having said that I do not know which databases support generated keys being returned during batch operations.

May be we could check on both `supportsBatchUpdates() && generatedKeyAlwaysReturned()` from the DatabaseMetaData ?

**Comment by SethTisue** [comment]
closing for inactivity. happy to reopen anytime if activity resumes, or someone could resubmit their own version.

**Pull request closed without merging**
