### PR TITLE
Adding support for Byte Array parameters. ISSUE-97

### PR DESCRIPTION
**Pull request by othreecr**
Fix for Issue 97: https://github.com/slick/slick/issues/97

### CODE REVIEW

**Comment by cvogt** [comment]
@trevorsibanda mind giving this a second look, maybe adding a test?

**Comment by trevorsibanda** [comment]
Tests are already covered in [JdbcTypeTest#testByteArray](https://github.com/slick/slick/blob/0358386eed2be1f369d829e081a4dec5e66825a5/slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/JdbcTypeTest.scala#L15)

**Comment by trevorsibanda** [comment]
LGTM

**Comment by cvogt** [comment]
@trevorsibanda I don't think this is tested. Otherwise, how did the tests pass before adding this? The test case you pointed to uses Array[Byte] in a Table class. The GetResult objects in this PR are for plain sql, which is different.

**Comment by cvogt** [comment]
looks like your test may have found a bug :)

**Comment by SethTisue** [comment]
closing for inactivity

**Pull request closed without merging**
