### PR TITLE
OracleProfile: Delete unused and incomplete OracleLocalTimeJdbcType from #1872

### PR DESCRIPTION
**Pull request by nafg**

### CODE REVIEW

**Comment by nafg** [comment]
@smootoo any idea about this?

**Comment by smootoo** [comment]
`OracleLocalTimeJdbcType` is an incomplete implementation. In particular it doesn't have a `setValue` method and so  `LocalTimeJdbcType.setValue` is being used. I think that is where the invalid month error is coming from.

**Comment by nafg** [comment]
@smootoo what do you suggest? Right now it's just dead code that was introduced in #1872, should it be deleted or do you want to fix it?

**Comment by smootoo** [comment]
You're right. It's dead code. I would suggest deleting it.

**Pull request merged**
