### PR TITLE
Try for the Select Distinct.

### PR DESCRIPTION
**Pull request by imcharsi**
Hi.  
At first, I did read https://github.com/slick/slick/issues/96
This work is for the Select Distinct. 
In the Slick, in order to use the select distinct, below syntax is used. 

```
qA.groupBy(t=>t).map(_._1)
```

And, result sql is like below. 

```
select x1.colA, x1.colB from (...) x1 group by x1.colA, x1.colB
```

In this work, below syntax is possible, also. 

```
qA.distinct
```

And, result sql is like below. 

```
select distinct x1.colA, x1.colB from (...) x1
```

This doesn't introduce any Node classes. Instead, add a one flag into Comprehension. 
And, the `.distinct` method is just a macro for `groupBy(t=>t).map(_._1)`.  
Thanks.

### CODE REVIEW

**Comment by kareblak** [comment]
Anything happening on this one?

**Comment by deanchen** [comment]
+1 would love to see distinct support in slick

**Comment by teldosas** [comment]
Is there maybe an overlab with this #1271 ?

**Comment by SethTisue** [comment]
closing for inactivity

**Pull request closed without merging**
