### PR TITLE
Issue #1641: SQL Server error with boolean columns

### PR DESCRIPTION
**Pull request by mpetruska**
* [x] adds test for and fixes https://github.com/slick/slick/issues/1641
* [x] replaces docker image `wnameless/oracle-xe-11g` with `oracleinanutshell/oracle-xe-11g` as the original was deleted from docker hub (see: https://github.com/wnameless/docker-oracle-xe-11g)
* [x] ready for review

### CODE REVIEW

**Comment by mpetruska** [comment]
Both pipelines failed:
- travis: `# if we got here, container startup has failed`
- appveyor: `sbt.ResolveException: download failed: de.johoop#sbt-testng-plugin;3.1.1!sbt-testng-plugin.jar`

Can we re-run them please?

**Comment by mpetruska** [comment]
The PR is ready for review, sorry for the noise and huge amount of commits.

**Comment by hvesalai** [comment]
I cherry-picked 912c3a04146bccefb0903de3873b46c924159982 to master already

**Comment by hvesalai** [comment]
Anybody up for review? I wouldn't want to merge it without one. @smootoo ?

**Comment by hvesalai** [comment]
can we squash merge? or does @mpetruska  want to clean the commits?

**Comment by mpetruska** [comment]
Closing in favor of #2014 .

**Comment by mpetruska** [comment]
@hvesalai I closed this PR and created one with a "clean" commit history; leaving the branch open, so it is easier to compare the contents of the two commits.
@smootoo Thanks you for the review; can I ask the favor of comparing the contents of the other, please?

**Pull request closed without merging**
