### PR TITLE
WIP: java time improvements, no more varchar mappings

### PR DESCRIPTION
**Pull request by WellingR**
This PR has been made to address many of the problems stated in #1987.
I have modified many of the Profiles to use the native support which many of the recent jdbc drivers have for the java.time types.

The basic idea is the following:
- `java.time.LocalDate` and `java.time.LocalDateTime` are derived from the `java.sql.Date` and `java.sql.Timestamp` types
- `java.time.LocalTime` is always mapped to the sql type `Time`, if the jdbc driver does not support fractional seconds the implementation is derived from the `java.sql.Time` type.
- `java.time.OffsetTime` has several variants it is either stored as `TIME WITH TIME ZONE` or `TIMESTAMP WITH TIME ZONE` (where the date part is ignored), if both of these types are not supported, an `INTEGER` is used to store this OffsetTime (with UTC offset) 
  Many databases convert the offset to UTC before storing, therefore the offset may be lost (this is documented this for each profile).
- `java.time.Instant`, `java.time.OffsetDateTime`, `java.time.ZonedDateTime` are stored as `TIMESTAMP WITH TIME ZONE` or `BIGINT` (epoch-millis). Depending on the database, timestamps are converted to UTC before storing them, therefore the offset and zone may be lost (again this is documented for each profile).

See https://github.com/slick/slick/pull/2035/files#diff-7ab0fb63ff939de7de8181745a064261 for the documentation per db profile

Todos
- [ ] Move, write and rewrite the documentation for these java time types
- [ ] Re-introduce the varchar mapping which can be isomorphic to the java.time.types, introduce a configuration option which allows users to use this mapping (is this needed?)
- [ ] Clean up the many todos in the code
- [ ] Implement these changes in the SQL server profile (I have not tested this profile yet)

Note: this PR includes the changes from #2024

### CODE REVIEW

**Comment by WellingR** [comment]
I would really like some feedback from @balagez @hvesalai @smootoo and others

Given this implementation, should these implicit JdbcTypes still be in scope by default, or should they be enabled though an explicit import (or perhaps included via the table code generator)?

Do we need to include configuration options to be able to use e.g. a VARCHAR mapping which has full-precision (including preservation of time offset and zone)?

**Comment by hvesalai** [comment]
Please remind me again why Instant needs the timezone? Instants are always in UTC as they measure nanoseconds since epoc in zulu-time.

**Comment by WellingR** [comment]
In theory an Instant could be stored using the local datetime in UTC. In that case slick can be perfectly capable of reading and writing the instant.

Other database clients which might read the same data will have more trouble, they will not make the assumtption that this timestamp was in fact written using the UTC timezone, so this might cause issues.
If we store the timestamp with the +00:00 time offset, then the actual time instant cannot be misinterpreted if a database client other than slick is used.

Actually postgres (an some other databases, judging from the observed behaviour) store the timestamp internally as UTC. The postgres docs state the following

> For timestamp with time zone, the internally stored value is always in UTC (Universal Coordinated Time, traditionally known as Greenwich Mean Time, GMT). An input value that has an explicit time zone specified is converted to UTC using the appropriate offset for that time zone. If no time zone is stated in the input string, then it is assumed to be in the time zone indicated by the system's TimeZone parameter, and is converted to UTC using the offset for the timezone zone.

For databases with this behaviour, the types Instant, OffsetDateTime and ZonedDateTime are similar, as these timestamps are always stored using the UTC +00:00 time offset.

**Comment by ashleymercer** [comment]
Bumping this.

@WellingR are you still interested in working on this? I think it would be a huge improvement. If not, I should have some time over the holidays to take a look.

@marcospereira what work would still need to be done to get this merged?

**Comment by WellingR** [comment]
@ashleymercer It has been more than one year ago since I last worked on this. If you would be willing to spend some time to finish this, then that would be awesome.

The biggest TODO is getting this to work for SQL server. I was unable to run these tests locally, so some tests are still broken, possibly because the test capabilities need to be configured correcly. Once that works, the documentation probably needs to be updated too.

**Comment by SethTisue** [comment]
Is anyone interested in picking this up...?

**Comment by SethTisue** [comment]
closing for inactivity

**Pull request closed without merging**
