### PR TITLE
Adding Typesafe connection config docs for postgres. ref issue #1861

### PR DESCRIPTION
**Pull request by adeperio**
Hi @d6y 

Just added some Postgresdb Typesafe config documentation, regarding #1861.

Let me know how that all looks to you, and if there was anything to fix, is missing, or incorrect.

Thanks :)

### CODE REVIEW

**Comment by d6y** [comment]
Looks good to me. Thank you!

I think we can also remove the duplicated (so possibly confusing) "mydb" section from the application.conf (https://github.com/adeperio/slick/blob/b3490bef0263473308314473898623f9b8f5ad40/doc/code/application.conf#L25-L35) ...if you have time for that.

**Comment by adeperio** [comment]
Hey @d6y ahh yep, wasn't sure if it was being used elsewhere. Just pushed up the change and updated the PR :)

**Comment by d6y** [comment]
@hvesalai this one is good to merge when you're ready for it.

Thank you @adeperio !

**Comment by adeperio** [comment]
No worries thanks @d6y :) Glad I could help! :)

**Pull request merged**
