### PR TITLE
Use sbt-version-scheme-enforcer-plugin

### PR DESCRIPTION
**Pull request by nafg**

### CODE REVIEW

**Comment by nafg** [comment]
@isomarcte can this be combined with [sbt-dynver](https://github.com/dwijnand/sbt-dynver)?

**Comment by isomarcte** [comment]
@nafg it looks like there was a bug if the version had a `+` in it in 2.1.0.2. I've got a PR up to fix it, https://github.com/isomarcte/sbt-version-scheme-enforcer/pull/54

I'll merge and release 2.1.0.3 as soon as it goes green.

Sorry about that

**Comment by isomarcte** [comment]
@nafg is that the issue you were seeing or was something else happening?

**Comment by nafg** [comment]
@isomarcte I wasn't seeing any issue; I hadn't tried it with sbt-dynver.

I was asking more based on the exchange that ended in this comment of yours: https://www.reddit.com/r/scala/comments/n4rnln/sbt_version_scheme_enforcer_plugin_automatically/gxad4r6?utm_source=share&utm_medium=web2x&context=3

I guess my concern is that if the version is simply a function of the previous version and the number of commits since, then Version Scheme Enforcer has no way to know what the current Change Type should be.

Let me continue this discussion on #2198.

**Comment by nafg** [comment]
One more point though: even when releasing, presumably one creates the tag _after_ CI has run. So even then, it won't work IIUC.

**Comment by isomarcte** [comment]
> I was asking more based on the exchange that ended in this comment of yours: https://www.reddit.com/r/scala/comments/n4rnln/sbt_version_scheme_enforcer_plugin_automatically/gxad4r6?utm_source=share&utm_medium=web2x&context=3

sbt-version-scheme-enforcer can work with sbt-dynver. I had initially thought there was an incompatibility, but it turns out there isn't. They are actually doing totally independent things. The only way the interact is that sbt-dynver takes control of the version string so the canonical way of increasing the MAJOR or MINOR version number is not longer valid, but there are other ways to accomplish this. See my post on: #2198

**Review by SethTisue — APPROVED** [review]
I'm not very familiar with sbt-version-scheme-enforcer, but I certainly don't object to trying it out here, especially since I see the author is around to help us out :-)

**Pull request merged**
