### PR TITLE
changed variable name from coffeeNames to coffeePrices

### PR DESCRIPTION
**Pull request by AlbaroPereyra**
Changed variable name from coffeeNames to coffeePrices so that it makes sense.

### CODE REVIEW

**Comment by d6y** [comment]
PR looks good to me 👍 

The build error is:

```
Unable to find image 'wnameless/oracle-xe-11g:latest' locally
docker: Error response from daemon: pull access denied for wnameless/oracle-xe-11g, repository does not exist or may require 'docker login'
```

The repo notes:

> Since 2019-Feb-13(the Valentine's day eve) this docker image has been removed by DockerHub due to the Docker DMCA Takedown Notice from the Copyright owner which is the Oracle.

From: https://github.com/wnameless/docker-oracle-xe-11g

**Comment by hvesalai** [comment]
There is an error here:

```
[error] /home/travis/build/slick/slick/doc/code/GettingStartedOverview.scala:96: not found: value coffeeNames
[error]       coffeeNames
[error]       ^
[error] one error found
```

**Comment by d6y** [comment]
@AlbaroPereyra the build has been working again for a while. Are you able to look at the compile error in the rest of `GettingStartedOverview.scala`?

**Comment by SethTisue** [comment]
closing for inactivity. happen to reopen if activity resumes

**Pull request closed without merging**
