### PR TITLE
Uses insert ignore for upsert.

### LINKED ISSUE #1627: insertOrUpdate compiles wrong statement on the table without soft syms.
insertOrUpdate compiles incorrect SQL statement when there is no other columns than primary key in the table.

I have a table which has only primary keys

``` sql
CREATE TABLE user_address (
  user_id INT,
  address_id INT,
  PRIMARY KEY (user_id, address_id)
);
```

``` scala
  class UserAddress(tag: Tag) extends Table[(Int, Int)](tag, "user_address") {
    def userId = column[Int]("user_id", O.PrimaryKey)
    def addressId = column[Int]("address_id", O.PrimaryKey)
    def * = (userId, addressId)
  }

  val userAddresses = TableQuery[UserAddress]
```

if i run this

``` scala
userAddresses.insertOrUpdate((uid, aid))
```

this generates following statement

``` sql
begin; update "user_address" set  where "user_id"=? and "addresss_id"=?; insert into "user_address" ("user_id","address_id") select ?,? where not exists (select 1 from "user_address" where "user_id"=? and "address_id"=?); end
```

,and it gives syntax error
`org.postgresql.util.PSQLException: ERROR: syntax error at or near "where"`

This is due to this line in `UpdateInsertBuilder`

``` scala
"update " + tableName + " set " + softNames.map(n => s"$n=?").mkString(",") + " where " + pkNames.map(n => s"$n=?").mkString(" and "),
```

If there is no column other than primary keys `set` clause will be empty. Is it intended or something need to be fixed?

I think `INSERT IGNORE` query would be more fit in this case, but I used insertOrUpdate since slick doesn't support it.

### PR DESCRIPTION
**Pull request by jkugiya**
This PR will close #1627.

### CODE REVIEW

**Comment by hvesalai** [comment]
@jkugiya isn't this same fix also applicable to other databases as well? I don't like the idea that with the MySQL profile things would work differently from the rest of the databases that do support insert ignore.

**Comment by hvesalai** [comment]
See also #1631

**Comment by jkugiya** [comment]
Expected behavior of my code is
- In case of there are only primary keys , it will be ignored
- If the primary key and other columns are mixed, update the columns other than the primary key when duplicates

```sql
mysql> create table mytest1(id VARCHAR(20));
Query OK, 0 rows affected (0.13 sec)
mysql> insert into mytest1 values ('a');
Query OK, 1 row affected (0.01 sec)
mysql> insert into mytest1 values ('a');
Query OK, 1 row affected (0.01 sec)
mysql> create table mytest2(id VARCHAR(20) primary key, value VARCHAR(20));
Query OK, 1 row affected (0.01 sec)
mysql> insert ignore into `mytest2` (`id`,`value`)  values ('aaa', 'uga') on duplicate key update `value`=VALUES(`value`);
Query OK, 0 rows affected (0.00 sec)
mysql> insert ignore into `mytest2` (`id`,`value`)  values ('aaa', 'ugaa') on duplicate key update `value`=VALUES(`value`);
Query OK, 2 rows affected (0.01 sec)
mysql> select * from mytest2;
+-----+-------+
| id  | value |
+-----+-------+
| aaa | ugaa  |
+-----+-------+
1 row in set (0.00 sec)
```
For **on duplicate key update** clause is MySQL's native syntax, and **insert on conflict** is postgresql's one, I think it is impossible to unify them in their native syntax. But I'll check the postgresql's behavior.
As such, what kind of behavior is expected for the function `insertOrUpdate`?

**Comment by hvesalai** [comment]
I think the behavior you have (i.e. insertOrUpdate is essentially insertOrIgnore for rows that have only primary keys) is good.

**Pull request merged**
