### PR TITLE
Only run inliner in CI

### PR DESCRIPTION
**Pull request by mdedetrich**
The Scala 2 inliner can cause issues when developing locally due to incremental compilation, i.e. from https://docs.scala-lang.org/overviews/compiler-options/optimizer.html#in-brief

> Don’t enable the optimizer during development: it breaks incremental compilation, and it makes the compiler slower. Only enable it for testing, on CI, and to build releases.

This PR only enables the inliner in CI and also prints a log statement statement that its enabled to make it clear.

### CODE REVIEW

**Comment by mdedetrich** [comment]
Working as expected, i.e. see https://github.com/slick/slick/actions/runs/7792797152/job/21251456956?pr=2889#step:7:30

**Comment by nafg** [comment]
Would prefer to keep one scala version pattern match but if you disagree it's ok

**Comment by mdedetrich** [comment]
> Would prefer to keep one scala version pattern match but if you disagree it's ok

Sure, I will also update the log statement

**Comment by mdedetrich** [comment]
PR updated with a pattern match, also updated log statement to mention which sbt module the inliner is being enabled for

**Comment by nafg** [comment]
It's still 2 pattern matches ;)

**Comment by mdedetrich** [comment]
@nafg Okay done, this version is actually cleaner/more correct since `scala2InlineSettings` is used in multiple places

**Review by nafg — APPROVED** [review]
Thanks!

**Pull request merged**
