### PR TITLE
Community docs / Related projects

### PR DESCRIPTION
**Pull request by cvogt**

### CODE REVIEW

**Comment by cvogt** [comment]
The Rough Experience with Slick http://t.co/g5a3JXYsJN

**Comment by cvogt** [comment]
https://github.com/muuki88/sbt-slick

**Comment by cvogt** [comment]
http://t.co/PfO0TULaih

**Comment by cvogt** [comment]
https://github.com/voidcontext/slick-generic-dao-example
https://github.com/satendrakumar06/slick-for-production

**Comment by cvogt** [comment]
https://gist.github.com/timcharper/037fb54fd788d42ad94f

**Comment by cvogt** [comment]
https://github.com/stephanfeb/scala-slick-postgres-mysql

**Comment by cvogt** [comment]
http://gavinschulz.com/posts/2016-01-30-common-model-fields-with-slick-3-part-i.html

**Comment by d6y** [comment]
It looks like many of these links are for Slick 1 and 2.  How about we move this to https://github.com/slick/slick.github.com (as suggested above), and create a bit of structure under "3rd-Party Documentation", here:

documentation slick 2016-03-03 08-42-39

...a page or section for Slick 1, 2 and 3.  We then have a place for each version, and we can start adding to the Slick 3 page?

Happy to take that on if it sounds useful and no-one else has a burning desire to do it :-)

Maybe even sub-divide each page into sections for blog posts, sample apps, tips 'n' tricks, etc.  Maybe not.

**Comment by cvogt** [comment]
+1

**Comment by d6y** [comment]
FYI: I'm porting this content into the slick web site.  Expect PR in the next few days,

**Comment by d6y** [comment]
I suggest closing this if and when https://github.com/slick/slick.github.com/pull/18 is merged.

**Comment by d6y** [comment]
Fixed in https://github.com/slick/slick.github.com/pull/18

**Pull request closed without merging**
