### PR TITLE
fixed forceInsertQuery issue (invoking with identical values issue)

### PR DESCRIPTION
**Pull request by coutoPL**
fix for https://github.com/slick/slick/issues/1487

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @coutoPL,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by cvogt** [comment]
LGTM. Would like a second review from @szeiger before merge.

**Comment by stephenjudkins** [comment]
Just ran into this bug. Any reason it hasn't been reviewed and merged? A fix in 3.1.x would be awesome. Anything I can do to help? @szeiger?

**Comment by cvogt** [comment]
@stephenjudkins I think this has just fallen under the radar. Merging now. For 3.1.x a PR would be great, if you want to see it :).

**Comment by cvogt** [comment]
(merging without additional review from @szeiger. This seems harmless enough. I am only uncertain about the topLevel=true change, but test pass, so let's go)

**Pull request merged**
