### PR TITLE
Revert ModelBuilder api, fixes #1075

### LINKED ISSUE #1075: Don't break the ModelBuilder api
This is the argument raised here: https://github.com/slick/slick/pull/1048

The recently merged changed api of the ModelBuilder is less regular, more verbose and slightly less powerful than the old one. The old model was consistent, beautifully regular, simple and proven. Why break the interface and change it?
- The old one had a clear Structure. The elements of the ModelBuilder exactly matched the structure of the Model and the code generator. Now they don't.
- Names are more verbose now. I can see your point thinking that TableBuilder may be easier to understand than Table. But I doubt it makes a big difference. Not calling them Builder makes the interface almost identical with the code generator, which is a big win. I never found confusion about this in the community with the code generator which has been around over a year. It is clear from the context which makes the new names redundant and unnecessarily verbose. Besides, every class and every method in the ModelBuilder contributes to building the model. Calling some of them builders is even inconsistent from some point of view. Finally, calling the factory methods createX and the class X is inconsistent with usual Scala code where the factory is the apply method of the companion, which has the same name as the class. I know we do that internally in the drivers, but haven't done that for external code so far.
- Not only names are more verbose, also one has to pass through all arguments now when overriding the TableBuilder, etc. Before they came from the context. More unnecessary work, more breakage in user code if we change the api.
- One thing that isn't possible without hackery anymore now is extending the interfaces of TableBuilder, ColumnBuilder etc. in a way that is visible through out the ModelBuilder, because it doesn't follow the virtual subclass pattern anymore.

I liked the old api, let's bring it back :). I think the new one is a step back. Let's revert that. The internals should of course use the new DBIO.

### PR DESCRIPTION
**Pull request by cvogt**
review by @szeiger 

I see that this does not contain https://github.com/slick/slick/pull/1058/ yet, which has been merged into slick:2.1-no-bin-compat. Is that branch still planned to be merged into master?

### CODE REVIEW

**Comment by cvogt** [comment]
There seems to be an order dependence in the tests from before this commit. See https://circleci.com/gh/slick/slick/tree/tmp%2Fundo-model-api-changes

**Comment by cvogt** [comment]
circleci fails reproducibly, but travis is fine. I can't reproduce the failure locally either. @szeiger Any idea?

**Comment by szeiger** [comment]
I have no idea what your circleci setup does, but I didn't see any failed tests in the PR that introduced this change. The tests are run in the order of the configurations defined in GenerateMainSources. It should be perfectly deterministic.

**Comment by szeiger** [comment]
This design with MTableExtended is a step backwards. It requires all data to be loaded upfront and prevents drivers from performing additional database calls to query the database for non-standard features. This was possible in 2.1 (because you could perform ad-hoc calls on a Session everywhere) and in my updated version which threads everything through DBIO.

**Comment by cvogt** [comment]
@szeiger fair point. I actually liked, that DBIO pushed me a bit to not do IO in the code that builds the model, but fetch all data upfront and feed it in. One approach would be to make it extensible in allowing to fetch arbitrarily more data upfront, but that may still not align with every use case. I'll rethink it in the next few days. What's the roadmap for 3.0 time wise?

**Comment by szeiger** [comment]
RC1 pretty much immediately, but I need to do the package refactoring and project refactoring first. I defer this any longer to wait for more PRs. At least in theory it shouldn't interfere with merging very much.

**Comment by cvogt** [comment]
Thinking about it more I am getting the feeling this points to a potential flaw in the DBIO api. Let's assume any kind of algorithm that is extensible. Let's say it is represented as a higher order function that does something and takes a function that is used multiple times somewhere in that algorithm. Example .map, but to make it more interesting, let's assume one where we have no choice in the return type.

    def someAlgorithm(f: SomeData => String): Int

Let's say we want to pass an f that uses SomeData and a database to compute the String. How would we do that in a single database session?

**Comment by szeiger** [comment]
You have to lift everything into DBIO up to the point where you run it:

    def someAlgorithm(f: SomeData => DBIO[String]): DBIO[Int]

Obviously, this is not possible if you have to implement a specific signature, but the same is true for explicit Session passing, unless you resort to hacks such as dynamicSession.

**Comment by cvogt** [comment]
This would have been possible with the old api without dynamic session hacks:

db.withSession{
 (new ModelBuilder{
    override def foo = /* ... do something involving db ... */
  }).buildModel
}

We could still do the same with the new model and an unsafe action. Is there any better way to do it with actions? I mean this is a more general problem with DBIO, we can't force everyone to write every algorithm that may potentially be extended with database operations at some point to use DBIO, even if it doesn't user database operations at the moment. What's the best solution? Unsafe sessions? In any case it seems like the "reverted model builder" doesn't have any deficiencies compared to the 2.1 one. Just a different way to write it down.

**Comment by szeiger** [comment]
Any solution that claims to provide a plain value but then requires database access to compute it, has to block. Until the JVM gets the necessary low-level features like coroutines or fibers, asynchronous I/O has to be expressed explicitly through types. Usually that means `Future` but if you want to compose database actions, you should use `DBIO` instead.

Composing Session-based operations with Futures would be possible but very fragile. You couldn't rely on lexical scope anymore (so you need to close the session explicitly) and reasoning about the required lifetime of the session would be even more difficult (your synchronous example only works because the session does not escape the withSession block, which is not enforced in any way). And you wouldn't gain much because you have to do the same cps-transformation of your code, whether you lift it into `Future` or into `DBIO`.

**Comment by cvogt** [comment]
Yep, makes sense. Considering this, I would suggest to keep DBIO out of the ModelBuilder, i.e. merge as is. It has the same power as before. When you make additional requests, you need to use an explicit session with the same risk of leaking it. But this should mostly happen at compile time, so it has less impact and not designing the ModelBuilder around DBIO makes it's design significantly simpler. The use case of having to use a database to fetch additional meta data is a reasonable, but an edge case, so I am fine telling people to use an explicit session. Besides, another way to cover many use cases is to transform the generated model afterwards, which is also non-intrusive for the ModelBuilder.

**Comment by szeiger** [comment]
> Just like before, when you make additional requests, you need to use an explicit session with the same risk of leaking it

Sessions will be removed in 3.1 (when all the now deprecated APIs that use them are gone).

**Comment by cvogt** [comment]
Ok, then jdbc connection.

**Comment by szeiger** [comment]
I am unconvinced. The current implementation does async I/O correctly and in an extensible way without resorting to hacks. The only downsides are that it changes some method names (in SPI used by drivers, not in API) and may require casts if you need to extend the implementation types with new members (if this really becomes an issue, we can add overridable type members to fix this in a source-compatible way). While the symmetry between model builder and code generator is nice, the model builder is used by driver implementers and the code generator is used by application developers.

**Comment by cvogt** [comment]
It is no more of a hack than the old session api as a whole. And since this case (injecting database ops into a lexical scope from the outside) isn't provided by the new api, the old api is the best we got. I know we may have to introduce one more DBIO variant to make this work. We should be able to enforce static, lexical scoping using macros rather than leaky dynamic scoping using a session value, if that's something you urgently want to fix for 3.0.0. It is not a regression in safety though, so I'd be happy to have it later, if leaky dynamic scoping for this particular edge case is easier right now.

Littering DBIO Monads over all interfaces that could potentially use database io at some point isn't the solution in my eyes.

Besides, I am doubtful if it really helps unless you really put it everywhere, which is not the case in your changed api. Let's assume computing the type of a particular column would require an additional database lookup to query some database specific additional meta data. How would you write that with the changed api? Or in other words, I'd like to see examples where that api makes anything simpler or safer without major convenience cuts. I am happy to changed my mind, but right now I don't see benefits, only disadvantages.

**Comment by cvogt** [comment]
@szeiger I saw you released 3.0.0-RC1 despite this being still open. Let's please discuss this and agree on a course of action before releasing the final or another RC.

**Comment by cvogt** [comment]
@szeiger Still looking to discuss this further until we find an agreement :).

**Comment by szeiger** [comment]
> It is no more of a hack than the old session api as a whole. And since this case (injecting database io into a lexical scope from the outside) isn't provided by the new api, the old api is the best we got.

Exactly. That's why we're getting rid of it. Any design that requires blocking I/O is a non-starter.

> We should be able to enforce static, lexical scoping using macros rather than leaky dynamic scoping using a session value, if that's something you urgently want to fix for 3.0.0.

That's what `dynamicSession` was and it's even worse. The fact remains that you cannot abstract over non-blocking I/O in such a way. You can use the cps or Scala Async plugin to make the syntax nicer but you still have to express it in your types.

> Littering DBIO Monads over all interfaces that could potentially use database io at some point isn't the solution in my eyes.
> Besides, I am doubtful if it really helps unless you really put it everywhere, which is not the case in your changed api.

If anything, this means that we need `DBIO` in even more places. Maybe all `create*Builder` methods should be lifted into `DBIO`. Since all the metadata that comes from I/O is passed into the builder, the `create*Builder` methods would be a good place to perform additional I/O before constructing a builder.

**Comment by cvogt** [comment]
>> It is no more of a hack than the old session api as a whole. And since this case (injecting database io into a lexical scope from the outside) isn't provided by the new api, the old api is the best we got.

> Exactly. That's why we're getting rid of it. Any design that requires blocking I/O is a non-starter.

Why do you say it is blocking? It doesn't protect from session leakage, but it doesn't seem blocking to me. Please explain.

Also you suggest to get rid of something without a fallback. We can't expect everyone to express all of their API using DBIO. Also, Scala is purposely a multi-paradigm language. It is a design decision to allow 

> > We should be able to enforce static, lexical scoping using macros rather than leaky dynamic scoping using a session value, if that's something you urgently want to fix for 3.0.0.

> That's what dynamicSession was and it's even worse. The fact remains that you cannot abstract over non-blocking I/O in such a way. You can use the cps or Scala Async plugin to make the syntax nicer but you still have to express it in your types.

I was talking about a macro that gives compile time guarantees about static scopes. I don't understand what you mean by this way dynamicSession, which is a runtime this with dynamic scopes.

>> Littering DBIO Monads over all interfaces that could potentially use database io at some point isn't the solution in my eyes.
>> Besides, I am doubtful if it really helps unless you really put it everywhere, which is not the case in your changed api.

> If anything, this means that we need DBIO in even more places. Maybe all create*Builder methods should be lifted into DBIO. Since all the metadata that comes from I/O is passed into the builder, the create*Builder methods would be a good place to perform additional I/O before constructing a builder.

This means every method that contributes to the model and could potentially use a database would need to use DBIO. The methods that compute column names, types, defaults, etc. Or you do it on coarser granularity like in the changes you did, but overriding functionality becomes more cumbersome, because of less re-use on top of the added noise for DBIO. The coarser granularity would also come at the price of a less regular api, which makes it harder to use.

If you really think it is worth it I can port this PR to every method using DBIO and see how it looks like. Seems impractical to me though. WDYT?

By the way, the discussion we are having here about DBIO, is only regarding the return types of all involved functions. The structure of the API into uniformly nested classes is unrelated to this.

**Comment by cvogt** [comment]
By the way, it is equally reasonable in the code generator to fetch additional meta data that can't be captured nicely in our current model. Would you suggest to change all methods in the code generator to DBIO as well? Or just prohibit people from doing that? Do you see the problem I am talking about?

**Comment by szeiger** [comment]
> Why do you say it is blocking? It doesn't protect from session leakage, but it doesn't seem blocking to me. Please explain.

If you want non-blocking, you need to wrap everything in a `Future`. You cannot avoid having this aspect leak into your types. And if you do that, you might as well use `DBIO` instead instead of `Future`.

> I was talking about a macro that gives compile time guarantees about static scopes. I don't understand what you mean by this way dynamicSession, which is a runtime this with dynamic scopes.

We had both static and dynamic scopes in the old API, and both are wrong. There is no way to do the required data flow analysis in a macro. The only real alternative to monads for I/O would be linear types or a proper effect system. And that would still not help you make it non-blocking unless you also throw fibers or coroutines into the mix.

> This means every method that contributes to the model and could potentially use a database would need to use DBIO. The methods that compute column names, types, defaults, etc.

You don't just use DBIO everywhere. The goal is to get a clean separation between pure code and code with I/O effects. In the current JdbcModelBuilder the I/O part consists of fetching the metadata and constructing the builders from it, then the builders can use that metadata in a pure way.

> Or you do it on coarser granularity like in the changes you did, but overriding functionality becomes more cumbersome, because of less re-use on top of the added noise for DBIO

Yes, absolutely, not being able to do ad-hoc I/O in code that is supposed to be pure is a restriction. And you need to design for this from the ground up, which is what I did with the rewrite of JdbcModelBuilder. And while the decision to completely remove all blocking APIs was not mine, I do agree with not using any such design in Slick itself.

**Comment by cvogt** [comment]
Alright, I am unconvinced that it is the right way to go, but let's not allow syntactically scoped sessions, as you suggested and see if we get away with it.

> There is no way to do the required data flow analysis in a macro.

Yeah, you are probably right about that.

> You don't just use DBIO everywhere. The goal is to get a clean separation between pure code and code with I/O effects. In the current JdbcModelBuilder the I/O part consists of fetching the metadata and constructing the builders from it, then the builders can use that metadata in a pure way.

I looked at your again. If we want to separate IO and pure code, whats the benefit of doing IO in the JdbcModelBuilder at all? My PR separates the two. Nothing stops you from preprocessing the model using IO before giving it to my pure JdbcModelBuilder. That looks even cleaner that partially doing IO in the model builder and partially being pure. WDYT?

**Comment by hvesalai** [comment]
@cvogt what is the statu son this? Close?

**Pull request closed without merging**
