### PR TITLE
Revert "Update dependency org.slf4j:slf4j-api to v2"

### PR DESCRIPTION
**Pull request by nafg**
Reverts slick/slick#2524

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @nafg,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by nafg** [comment]
Resigned

**Comment by nafg** [comment]
Signed

**Comment by francisdb** [comment]
No rationale on why this was reverted?

**Comment by nafg** [comment]
@francisdb see #2542 

It should be upgraded in 3.5.0 though

**Pull request merged**
