### PR TITLE
Remove ability to use sample projects standalone

### PR DESCRIPTION
**Pull request by nafg**
Simplifies the build and makes it easier to simplify it further subsequently

### CODE REVIEW

**Comment by nafg** [comment]
@slick/slick-maintainers anyone?

**Comment by SethTisue** [comment]
no objection from me

**Comment by nafg** [comment]
I don't have the ability to merge until someone other than me submits an approval review

**Review by SethTisue — APPROVED** [review]

**Comment by nafg** [comment]
Thanks!

**Pull request merged**
