### PR TITLE
Add strip margin functionality to SQL-interpolated strings

### PR DESCRIPTION
**Pull request by mwegrz**
Implements #1309

### CODE REVIEW

**Comment by cvogt** [comment]
I am skeptical of this change. Why do we need stripMargin? The SQL is still valid if written multi-line without using strip-margin isn't it?

**Comment by mwegrz** [comment]
Yes, SQL is valid with arbitrary number of white characters inserted between clauses but it might not look the same when printed or logged. There might be use cases where one would like to keep same formatting both in the code and log output.

**Comment by cvogt** [comment]
that's a good explanation. LGTM. I'll wait for @szeiger to merge

**Comment by jpfuentes2** [comment]
The use-case stated by @mwegrz is exactly why I've copy pasted this for now as an implicit enrichment. Thanks!

**Comment by FeiWongReed** [comment]
What's the problem to merge that simple fix?..

**Comment by kmetsalu** [comment]
Also interested in this capability.

**Comment by pshirshov** [comment]
AAaaaanybody?

**Comment by nafg** [comment]
Why?

**Comment by pshirshov** [comment]
What's a problem to merge such a trivial change.

**Comment by cvogt** [comment]
simple indeed and there there seems to be demand. not holding this up longer. merged

**Pull request merged**
