### PR TITLE
#1424 issue union limit

### PR DESCRIPTION
**Pull request by dwene**
Attempting to finish the work started last year in PR: https://github.com/slick/slick/pull/1538

> union with limit was not properly supported by at least
> 
> postgres
> derby
> sqlite
> Hsqldb
> H2
> General fix is simply to add parenthesis on both side, special case must be done for derby and sqlite
> 
> derby related issue : https://issues.apache.org/jira/browse/DERBY-2374
> sqlite related issue : http://stackoverflow.com/questions/10812910/combine-two-statements-with-limits-using-union

https://github.com/slick/slick/issues/1424

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @dwene,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by spilliton** [comment]
👍 👍 👍 👍

**Comment by dwene** [comment]
@maquessime

**Comment by cvogt** [comment]
Awesome stuff :)

**Pull request merged**
