### PR TITLE
Scala 2.11.8 -> 2.11.12

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
ping @cvogt

**Comment by sullis** [comment]
any update here?

**Comment by cvogt** [comment]
build failed, restarted

**Comment by sullis** [comment]
ping @cvogt

**Comment by SethTisue** [comment]
is the CI failure real, or just an intermittent thing hitting "restart" might clear up...?

**Comment by hvesalai** [comment]
@I'll restart Travis

**Comment by hvesalai** [comment]
Looks like the same DB2 thing that has been pestering us for some time. It should be transient.

**Pull request merged**
