### PR TITLE
Fix `getOrElse` type inference issue in Scala 3, closes #2761

### LINKED ISSUE #2761: `getOrElse` type inference issue in Scala 3
**STEPS TO REPRODUCE:**

`build.sbt`

```scala
scalaVersion := "3.3.0"

crossScalaVersions += "2.13.11"

libraryDependencies += "com.typesafe.slick" %% "slick" % "3.5.0-M4"
```

`Main.scala`

```scala
package example

import slick.jdbc.JdbcProfile

trait Main {
  val profile: JdbcProfile

  import profile.api._

  def rep1: Rep[Option[Boolean]]

  def rep2: Rep[Boolean]

  def rep3: Rep[Boolean] = rep1.getOrElse(rep2)
}
```

**EXPECTED RESULT:**

compile success

**ACTUAL RESULT:**

compile error **only Scala 3** (success with Scala 2.13 and 2.12)

```
[error] -- [E007] Type Mismatch Error: /Users/kenji/slick-getOrElse-issue/Main.scala:14:27 
[error] 14 |  def rep3: Rep[Boolean] = rep1.getOrElse(rep2)
[error]    |                           ^^^^^^^^^^^^^^^^^^^^
[error]    |Found:    slick.lifted.ShapedValue.Unconst[slick.lifted.Rep[Boolean],
[error]    |  slick.lifted.Rep[Boolean]]
[error]    |Required: slick.lifted.Rep[Boolean]
[error]    |
[error]    |Note: a match type could not be fully reduced:
[error]    |
[error]    |  trying to reduce  slick.lifted.ShapedValue.Unconst[slick.lifted.Rep[Boolean],
[error]    |  slick.lifted.Rep[Boolean]]
[error]    |  failed since selector  slick.lifted.Rep[Boolean]
[error]    |  does not match  case slick.lifted.ConstColumn[t] => slick.lifted.Rep[t]
[error]    |  and cannot be shown to be disjoint from it either.
[error]    |  Therefore, reduction cannot advance to the remaining case
[error]    |
[error]    |    case Any => slick.lifted.Rep[Boolean]
[error]    |
[error]    | longer explanation available when compiling with `-explain`
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

### PR DESCRIPTION
**Pull request by OlegYch**
Note: I have no idea what `Unconst` is doing but this fixes the issue

### CODE REVIEW

**Comment by nafg** [comment]
I'm confused, I thought it's fixed in M4?

**Comment by nafg** [comment]
I don't either know offhand exactly what Unconst is for, but with this change its name is no longer accurate.

**Comment by OlegYch** [comment]
@nafg #2761 is actually a problem caused by fix to #2674

the change actually aligns scala3 implementation with scala2 https://github.com/slick/slick/blob/503c6c966f86739725f8788df21cce5e153ea27f/slick/src/main/scala-2/slick/lifted/ShapedValue.scala#L96 so i think the name is still accurate 

perhaps @szeiger can shed some light on it

**Comment by OlegYch** [comment]
oh, i get it, `Unconst` means that it removed `ConstColumn` ...

**Comment by mdedetrich** [comment]
> @nafg #2761 is actually a problem caused by fix to #2674
> 
> the change actually aligns scala3 implementation with scala2
> 
> https://github.com/slick/slick/blob/503c6c966f86739725f8788df21cce5e153ea27f/slick/src/main/scala-2/slick/lifted/ShapedValue.scala#L96
> 
> so i think the name is still accurate
> perhaps @szeiger can shed some light on it

I am not sure if its related, but we currently trying to add Scala 3 support to a Slick connector at Pekko and we are getting flaky test errors only for Scala 3, see https://github.com/apache/incubator-pekko-connectors/pull/223#issuecomment-1692537114

**Comment by nafg** [comment]
With the new definition of Unconst it seems pointless. Is it really needed?

**Comment by nafg** [comment]
or maybe scala 2 should keep `type Unconst[P, P2] = P` and scala 3 essentially gets `type Unconst[P, P2] = P2` ?

**Comment by nafg** [comment]
Unconst is only used in getOrElse, where it says
```
 def getOrElse[M, P2 <: P](default: M)(implicit shape: Shape[FlatShapeLevel, M, ?, P2], ol: OptionLift[P2, O]): ShapedValue.Unconst[P, P2] = {
    // P2 != P can only happen if M contains plain values, which pack to ConstColumn instead of Rep.
    // Both have the same packedShape (RepShape), so we can safely cast here:
    val r = fold[P, P](shape.pack(default): P)(identity)(shape.packedShape.asInstanceOf[Shape[FlatShapeLevel, P, ?, P]])
    r.asInstanceOf[ShapedValue.Unconst[P, P2]]
  }
```

I don't understand the comment.

Also since that's the only place it's used I don't know why it's in ShapedValue.

**Comment by nafg** [comment]
You could go for the full implication of this change. But have you tried other ways, like adding other match cases or something?

Also what happens if you keep your change but don't change the P2s to P?

Also what happens if scala 2 would use P2?

**Comment by OlegYch** [comment]
`type Unconst[P, P2] = P2` on scala2 breaks #2674 
`  type Unconst[P, P2] = P match {
    case Rep[t] => Rep[t]
    case _ => P
  }
` and   `type Unconst[P, P2] = P2 match {
    case Rep[t] => Rep[t]
    case _ => P2
  }` behave the same on scala3

**Comment by OlegYch** [comment]
in fact removing P2 entirely seems to be harmless

**Comment by OlegYch** [comment]
@nafg i did some cleanup, and think it is ready to be merged

**Review by nafg — APPROVED** [review]
Sorry for the delay, I probably had feedback that I don't recall but I want to do another milestone release so let's just get it in

**Pull request merged**
