### PR TITLE
Codegen: Suppress output of schema.create if ddlEnabled is false

### PR DESCRIPTION
**Pull request by schmitch**
Currently the Codegenerator couldn't be configured to disable ddl generation.
I introduced a new val called ddlEnabled which could be set to false to suppress ddl generation on customized SourceCodeGenerators

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @schmitch,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by cvogt** [comment]
@schmitch could you please sign the CLA and amend your commit undoing the whitespace changes to avoid unnecessary git history disruptions? thx

**Comment by schmitch** [comment]
Sorry Sublime Text somehow screwed it.

**Comment by cvogt** [comment]
LGTM

**Comment by cvogt** [comment]
@schmitch thank you for your contribution. will be in the next slick release 3.1. @szeiger any ETA for that?

**Pull request merged**
