### PR TITLE
Add custom 'circle.yml' for running all the test using the oraclejdk8

### PR DESCRIPTION
**Pull request by xavier-fernandez**

### CODE REVIEW

**Comment by szeiger** [comment]
Does it make sense to keep the Circle CI builds at all? @cvogt set this up for a quick validation run but they seem to be slower now than the Travis builds.

**Comment by xavier-fernandez** [comment]
@szeiger In my opinion Circle CI build do not make sense at all if Travis works successfully.

On the other hand, I need either Circle CI fixed or removed for the PR #1026

**Comment by cvogt** [comment]
if this unblocks something, let's merge it. We can discuss removing later :).

**Comment by cvogt** [comment]
LGTM

**Pull request merged**
