### PR TITLE
Merge 3.1 to master for 3.2.0-M2

### PR DESCRIPTION
**Pull request by szeiger**

### CODE REVIEW

**Comment by szeiger** [comment]
WTF is going on now? AppVeyor can't find sbt again (after I fixed it yesterday), and now Travis is also broken for no obvious reason.

**Comment by szeiger** [comment]
Several failures around zip joins on SQL Server. Apparently https://github.com/slick/slick/pull/1661/commits/5cfbd2ef0d11cf0f331d124246bf1f7f6ea1cd25 interacts badly with some other change in master.

**Comment by szeiger** [comment]
Or more likely: It never worked on SQL Server. 3.1 still needs Slick Extensions for that, so it wasn't routinely tested in CI.

**Comment by szeiger** [comment]
@smootoo Any idea what's up with the Oracle connection? I've occasionally seen this problem before but a restart always fixed it. Now the pool startup consistently hangs even though the docker image is up: https://travis-ci.org/slick/slick/builds/180734597

**Comment by smootoo** [comment]
@szeiger I'll take a look at this over the weekend

**Comment by szeiger** [comment]
@smootoo Thanks. Looks like it's working again now (without any changes to the branch)

**Comment by smootoo** [comment]
For the appveyor fails, that looks like a real break with the SQLServer profiles. The sorting on the JoinTest.testZip is broken. It’s probably not too hard to fix, but in the 6 months since I last did any scala dev work, all my SQLServer VMs seemed to have stopped working :-( I’ll need to configure a new test environment, which will take a few days, but I’m happy to take a look at it if you would like?
https://ci.appveyor.com/project/slick/slick/build/1.0.109#L1155
[error] Test com.typesafe.slick.testkit.tests.JoinTest.testZip[sqlserver2014-sqljdbc] failed: java.lang.AssertionError: expected:<List((1,0), (2,1), (3,2), (4,3))> but was:<Vector((1,0), (3,1), (2,2), (4,3))>, took 0.047 sec

Regarding the pool hanging on startup of Oracle. In my testing, I’ve not been able to reproduce it, but can see it hanging on the link you provided. It’s trying to acquire a database connection through Hikari. Even if the docker image had stalled, I would have expected a timeout, but looking at the configuration options I put into the test config, they are very conservative. A 10 min connection timeout is the same as the travis stalled build timeout threshold. I'll try some less pessimistic Hikari connection timeouts and maybe the pool can handle those connection timeouts and let the builds complete.

**Comment by szeiger** [comment]
The SQL Server failures are very likely due to https://github.com/slick/slick/pull/1661/commits/5cfbd2ef0d11cf0f331d124246bf1f7f6ea1cd25. I'm working my way down through the rabbit hole to fix them. After making everything work again with updates on my Windows VM, OSX, Travis, changes in Slick 3.1 and Slick master (the last of which was https://github.com/slick/slick/pull/1582#issuecomment-264895878), I can finally reproduce them locally.

**Comment by szeiger** [comment]
At last, the AppVeyor build passed. Once the others are green, too, I'll merge and cut the release, then cherry-pick the last commit back to 3.1.

**Pull request merged**
