### PR TITLE
fixes issue #1447: runtime exception when using asColumnOf[BigDecimal] with mysql

### PR DESCRIPTION
**Pull request by dnagoda**
Let me know if you also need the same fix on master. I'm using 3.1.1, so that's where I fixed it first.

### CODE REVIEW

**Comment by cvogt** [comment]
LGTM. @szeiger ?

**Comment by dnagoda** [comment]
Is there anything else that I can do on this pull request to get it merged?

**Comment by trevorsibanda** [comment]
Is there anything else needed here before this is merged ?

**Comment by cvogt** [comment]
Looks good to me. However we usually only fix regressions in old versions. This means this fix should go into master instead. I changed the base, but looks like there is a merge conflict. @trevorsibanda mind rebasing this on master?

**Comment by cvogt** [comment]
(might need a fresh PR, since this is from dnagoda's branch)

**Comment by dnagoda** [comment]
Looks like it'll need an new PR to me also. The conflict is that slick/src/main/scala/slick/driver/MySQLDriver.scala no longer exists and the changes I made there would need to be made in slick.jdbc.MySQLProfile.scala instead. What's the easiest way for me to do that and provide a PR for you?

**Comment by dnagoda** [comment]
Realized I was over thinking it. Pull request should be updated.

**Comment by cvogt** [comment]
merged! @szeiger, if we do another RC for 3.2.0, we could cherry-pick it.

**Pull request merged**
