### PR TITLE
add scala-steward `buildRoots` setting

### PR DESCRIPTION
**Pull request by xuwei-k**
https://github.com/scala-steward-org/scala-steward/blob/28d9752eb16916af8ad19c259cb8743ed6cf4cdf/docs/repo-specific-configuration.md

### CODE REVIEW

**Comment by nafg** [comment]
This is great if I revert #2250 due to https://github.com/slick/slick/issues/2193#issuecomment-875947935

But right now it can only be run from the root, so I don't see the point?

Has anything in particular lagged?

**Comment by nafg** [comment]
@xuwei-k please explain

**Comment by xuwei-k** [comment]
There are some old dependencies in sample projects `build.sbt`

- https://github.com/slick/slick/blob/ebac03805f85f69829a15b48505439b5b67cf788/samples/slick-plainsql/build.sbt#L2-L3
- https://github.com/slick/slick/blob/ebac03805f85f69829a15b48505439b5b67cf788/samples/hello-slick/build.sbt#L2-L4
- https://github.com/slick/slick/blob/ebac03805f85f69829a15b48505439b5b67cf788/samples/slick-multidb/build.sbt#L2-L4
- https://github.com/slick/slick/blob/ebac03805f85f69829a15b48505439b5b67cf788/samples/slick-testkit-example/build.sbt#L2-L4

scala-steward use [sbt-updates](https://github.com/rtimush/sbt-updates) plugin. I think sbt-updates can't detect sample projects `build.sbt` dependency updates in slick.


### `dependencyUpdate` in root

```
[info] No dependency updates found for slick-codegen
[info] No dependency updates found for slick-root
[info] No dependency updates found for site
[info] Found 1 dependency update for slick-hikaricp
[info]   com.zaxxer:HikariCP : 4.0.3 -> 5.0.1
[info] No dependency updates found for slick
[info] Found 8 dependency updates for slick-testkit
[info]   com.h2database:h2:codegen                  : 1.4.200                    -> 2.1.210             
[info]   com.h2database:h2:test                     : 1.4.200                    -> 2.1.210             
[info]   com.microsoft.sqlserver:mssql-jdbc:codegen : 7.2.2.jre11 -> 7.4.1.jre12 -> 10.1.0.jre17-preview
[info]   com.microsoft.sqlserver:mssql-jdbc:test    : 7.2.2.jre11 -> 7.4.1.jre12 -> 10.1.0.jre17-preview
[info]   org.apache.derby:derby:codegen             : 10.14.2.0   -> 10.15.2.0                          
[info]   org.apache.derby:derby:test                : 10.14.2.0   -> 10.15.2.0                          
[info]   org.hsqldb:hsqldb:codegen                  : 2.5.2       -> 2.6.1                              
[info]   org.hsqldb:hsqldb:test                     : 2.5.2       -> 2.6.1                              
[success] Total time: 4 s, completed 2022/01/18 7:38:53
```

### `dependencyUpdate` in `samples/hello-slick`

```
info] Found 4 dependency updates for hello-slick
[info]   com.h2database:h2            : 1.4.200                     -> 2.1.210
[info]   org.scala-lang:scala-library : 2.12.15           -> 2.13.8           
[info]   org.scalatest:scalatest:test : 3.2.6   -> 3.2.10                     
[info]   org.slf4j:slf4j-nop          : 1.7.26  -> 1.7.33                     
[success] Total time: 1 s, completed 2022/01/18 7:39:59
```

**Comment by xuwei-k** [comment]
>  sbt-updates can't detect sample projects build.sbt dependency updates in slick.

Should we change aggregate setting? 🤔 

```diff
--- a/build.sbt
+++ b/build.sbt
@@ -249,7 +249,7 @@ lazy val site =
 lazy val root =
   project
     .in(file("."))
-    .aggregate(slick, codegen, hikaricp, testkit, site)
+    .aggregate(slick, codegen, hikaricp, testkit, site, `sample-hello-slick`, `sample-slick-plainsql`, `sample-slick-multidb`, `sample-slick-testkit-example`)
     .settings(
       name := "slick-root",
```

**Comment by nafg** [comment]
I moved the samples to their own repos

**Pull request closed without merging**
