### PR TITLE
Fix mapTo for case classes with companion objects

### LINKED ISSUE #1873: The mapTo macro doesn't compile when target case class has a companion object
The mapTo method is in slick.lifted.ShapedValue, the associated macro is ShapedValue.mapToImpl.

Using the mapTo macro fails to compile whenever you target a case class that have a companion object, even if that companion object is completely empty. It gives the following error:
```
Error:(20, 40) value tupled is not a member of object slicktemplate.App.Message
    def * = (sender, content, id).mapTo[Message]
```

Here is a test case: 
```
object App {
  import slick.jdbc.H2Profile.api._

  final case class Message(
    sender:  String,
    content: String,
    id:      Long = 0L)

  object Message {}

  final class MessageTable(tag: Tag)
      extends Table[Message](tag, "message") {

    def id      = column[Long]("id", O.PrimaryKey, O.AutoInc)
    def sender  = column[String]("sender")
    def content = column[String]("content")

    def * = (sender, content, id).mapTo[Message]
  }
}
```
Remove the 'object Message{}' line and it compiles.

I'm using Slick 3.2.2, Scala 2.12.4 and sbt 1.0.4. I have checked with H2Profile and PostgresProfile, I get the same error.

### PR DESCRIPTION
**Pull request by jabrouwer82**
Change the `mapToImpl` macro use a tupled `apply` method instead of directly calling `tupled`.
This allows manually defined companion objects for case classes used in `mapTo`.
Fixes #1873

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jabrouwer82,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by jabrouwer82** [comment]
I updated the macro to check for an existing `tupled` method, which is likely to either from a synthetic companion object or was explicitly written by users. If a `tupled` method already exists, then it is directly used, meaning this macro should resolve identically for any code written before this change that already compiled.

I left method-local companion objects broken, since it seems they can't be correctly inspected without more effort. They're also probably a niche use case, so I'm unconcerned. Let me know if the extra tests aren't appreciated!

It looks like y'all's CI is broken because openjdk 8 fails to install

**Review by hvesalai — APPROVED** [review]
Looks good to me. Let's wait for a while if somebody else wants to also review

**Review by renatocaval — APPROVED** [review]
Thanks @jabrouwer82, this is a good addition. 

I do think though that we should target it for v3.4.0. 

We are planning to cure v3.3.3, but that it's a bug fix release. New APIs can be added to v3.4.0.

**Comment by nafg** [comment]
@jabrouwer82 could you look into whether the docs at https://scala-slick.org/doc/3.4.0-SNAPSHOT/ (sources at https://github.com/slick/slick/tree/main/doc/paradox) should be updated?

**Comment by nafg** [comment]
Sorry I didn't realize you already had. Never mind then. :facepalm:

**Pull request merged**
