### PR TITLE
Support for savepoints within transactions

### PR DESCRIPTION
**Pull request by hvesalai**

### CODE REVIEW

**Comment by hepin1989** [comment]
@hvesalai any updates?

**Comment by hvesalai** [comment]
@szeiger or @cvogt know better. Is this pull request going to be merged in or has the architecture changed so much that it is no longer valid?

**Comment by szeiger** [comment]
The old session API is gone in 3.2. This doesn't make sense any more in its current form. We need to go back to the drawing board.

It seems to me that savepoints are only useful in the context of error recovery. If you don't want to recover from an error, `transactionally` should be all you ever need. It will ensure that a DBIOAction fails or succeeds atomically but recovery does not compose if all you have is `transactionally` because you can only recover at the outermost layer (where the actual database transaction is).

Therefore, a savepoint API might look something like this (simplified):

    trait DBIO[T] {
      def recoverWith(f: Throwable => DBIO[T])(implicit ec: ExecutionContext): DBIO[T]
    }

The interpreter would have to support trampolining for this action (like it does for everything in 3.2) and create savepoints on demand. The `recoverWith` combinator can be defined together with `transactionally` to leave non-transactional backends out of the picture.

What about streaming? Unlike `transactionally`, this action probably has to be non-streaming. I don't see any way of making it work with Reactive Streams.

WDYT?

**Comment by hvesalai** [comment]
I don't quite understand how that would work? Could you give an example how recoverWith would be used.

When I wrote the original code, we had some real use for withSavepoint. Now there is only this left:

```scala
        session.withTransaction {
          try {
            withSavepoint {
              Q.updateNA(s"ALTER TABLE $name RENAME TO $backupName").execute
            }
          } catch { case _: Exception => } // ignore

          Q.updateNA(s"ALTER TABLE $newName RENAME TO $name").execute
        }
```

**Comment by hepin1989** [comment]
`recoverWith` will work which means there will be an implicit savepoint before you call the recoverWith.

**Comment by szeiger** [comment]
`recoverWith` is the equivalent of error handling in the DBIO monad. Maybe it should even take a `PartialFunction` for this reason. Your code would translate to this:

    sqlu"ALTER TABLE #$name RENAME TO #$backupName".recoverWith {
      case _: Exception => DBIO.successful(0)
    }.andThen(sqlu"ALTER TABLE #$newName RENAME TO #$name").transactionally

Generally the beginning of the LHS of `recoverWith` is marked with a savepoint although in this special case it's not really needed. If the interpreter is smart enough it could recognize that the savepoint is identical to the beginning of the transaction and thus omit it.

(Is `recoverWith` a good name? It would be worthwhile to investigate other monadic APIs to see how they call it.)

**Comment by hvesalai** [comment]
Please see #1655

**Pull request closed without merging**
