### PR TITLE
Replace sbt-version-scheme-enforcer with sbt-version-policy

### PR DESCRIPTION
**Pull request by nafg**
sbt-version-scheme-enforcer is better IIUC when you're setting `version` explicitly

Instead, I'm setting the version automatically based on versionPolicyIntention and
an sbtdynver.GitDescribeOutput.

This obviates the need for `versionCheck`, which doesn't seem to support PVP anyway,
and means that after a PR the only thing that might need to be updated is
`versionPolicyIntention`.

### CODE REVIEW

**Comment by nafg** [comment]
Not sure why CI was fine until now, but the issue is fixed in #2321.

Let's get that merged first.

**Review by SethTisue — APPROVED** [review]
I'm not familiar with sbt-version-scheme-enforcer, but sbt-version-policy is widely used, including in many other repos I'm involved with, so it seems like a safe choice.

Not sure about every detail of the changes, but happy to hit "approve" regardless, we can always make adjustments later.

**Comment by nafg** [comment]
The issue with sbt-version-policy was mainly that `versionCheck` doesn't work with PVP (and the naming of `Compatibility.*` values don't seem be right, hence my renaming import). Since I'm computing `version` from `versionPolicyIntention`, running `versionCheck` seems to be pointless. I think in the past it didn't support PVP altogether but I think now it's okay with it.

The main feedback I would like (from anyone) is just about the approach of computing `version` from `versionPolicyIntention`. The advantage is less housekeeping during a release lifecycle -- instead of updating `version` ever, all you have to do is (1) after a release, set `versionPolicyIntention` to `BumpMinor`, (2) a breaking PR needs to change `versionPolicyIntention` to BumpMajor, and game-changing PR (e.g. Scala 3 related changes) needs to set it to BumpEpoch.

Other than that I still need to test it more thoroughly. I should start by writing up a list of scenarios to test. I guess it's mainly on or after release and prerelease tags. I should set this PR to draft so it isn't merged first.

**Comment by nafg** [comment]
I have code for sbt-ci-release locally, but it doesn't make sense to push before this is merged.

**Comment by nafg** [comment]
Hmm, maybe closing-reopening won't help for appveyor/branch. I would have to rebase locally and force-push.

I might not have time to test and rebase until next Sunday.

**Comment by nafg** [comment]
> I'm not familiar with sbt-version-scheme-enforcer

btw in case this clears up any confusion: I added sbt-version-scheme-enforcer recently -- see the release planning issue (it's been a while since the discussion, I know)

@SethTisue do you think `continuous-integration/appveyor/branch` should be made to not block PRs? I believe the difference between /pr and /branch is whether it tests the branch before merge or after merge. I think github actions only tests it after a merge commit. It's nice to test without the merge (for one thing, I would imagine that if a PR has merge conflicts it's the only one that can run), but I don't know if we need it to be a prerequisite. What do you think?

**Comment by SethTisue** [comment]
I'm fine with treating the "branch" test as merely advisory.

**Comment by nafg** [comment]
> I'm fine with treating the "branch" test as merely advisory.

I don't think I can make that change

**Comment by nafg** [comment]
Refactored.

I wrote and included an ammonite script that tests the logic in different scenarios. I'm not sure if it should really be committed, and if yes in what format (e.g. ammonite script vs. sbt task vs. bash script etc.), and if it should be part of CI.

Opinions on that, and on the implementation itself, please?

**Comment by nafg** [comment]
IIRC there should be a way to make a CI step only run when certain files are changed, so I could make the test get run whenever build.sbt or project/Versioning.sbt change

**Comment by SethTisue** [comment]
> Opinions on that, and on the implementation itself, please?

(Sorry, no opinion... perhaps someone else would like to weigh in.)

**Comment by nafg** [comment]
@octonato, @hvesalai, any thoughts on this approach?

**Pull request merged**
