### PR TITLE
Dependency update

### PR DESCRIPTION
**Pull request by dant3**
Hi,

I've updated some dependencies and sbt to include latest bugfixes/perfomance improvements.
Unfortunately for now not all of these went smooth, in particular:

* Update of sqlite driver up to `3.8.11.2` fails some tests. Will investigate on this one.
* Update of hsqldb driver up to `2.2.9` fails some tests as well (note that current version is `2.3.3` and changelog is quite impressive)

Note that for now I didn't included versions that causing failures, so that it's possible to merge whats working, and then deal with what needs more attention.

### CODE REVIEW

**Comment by dant3** [comment]
Looks like CircleCI still doesn't have sbt 0.13.11
This can be fixed by installing it manually before building, like

```
dependencies:
  pre:
    - mkdir -p ~/.sbt/.lib/0.13.11/
    - curl -L -o ~/.sbt/.lib/0.13.11/sbt-launch.jar https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.11/sbt-launch.jar
```

If nobody objects I'll include this change in this PR as well.

**Comment by cvogt** [comment]
what if we go to 0.13.10 for now instead?

**Comment by dant3** [comment]
Looks like it's the same for sbt 0.13.10

**Comment by cvogt** [comment]
any reason to upgrade sbt at all right now :)?

**Comment by dant3** [comment]
I was hoping to see if slick works with dotty at all, and sbt 0.13.11 have initial support for dotty. Other than that there is no particular reason for that change. Can opt for it to go in other branch if I happen to go far with dotty build.

**Comment by cvogt** [comment]
Let's delay the sbt update in master then. Curious to see your dotty experiments. do share when you get to it :)

**Comment by dant3** [comment]
Also incremental compile time is better with sbt 0.13.11

**Comment by dant3** [comment]
We're green now \o/

**Comment by cvogt** [comment]
LGTM (forgot to wait for a second one)

**Pull request merged**
