### PR TITLE
Improve Build

### PR DESCRIPTION
**Pull request by rfranco**
## Improve Build

I'd like to help slick so i'm starting clean and improve the build system using `Akka`, `Play` and `Spray` projects as reference and use sbt 0.13.7 features.

Features:
- [X] rename build.sbt to plugins.sbt
- [X] split Build in small build.sbt for each project
- [X] BaseSettings AutoPlugins
- [X] Move doc to a project slick-docs

Any doubts or suggestion to do please comment my work.

### CODE REVIEW

**Comment by rfranco** [comment]
@szeiger or @cvogt Can docs be moved to a project outside src folder? as Akka does, there is a project `akka-docs`.

**Comment by rfranco** [comment]
@szeiger or @cvogt wait answer

**Comment by cvogt** [comment]
@szeiger WDYT? I am in favor of breaking up the sbt file like this. Didn't check all the details of the changes.

@rfranco Please end files in a new lines as in POSIX standard.

**Comment by rfranco** [comment]
@cvogt sure, maybe i'll add scalariform for the project. WDYT?

**Comment by cvogt** [comment]
I am not a big fan of automated formatting tools. I personally indent for readability not for conformity.

**Comment by rfranco** [comment]
what is the sbt-sdlc Plugin? why do need that?

**Comment by cvogt** [comment]
https://github.com/typesafehub/sbt-sdlc  makes sure the scaladoc links work in our documentation

**Comment by cvogt** [comment]
make sure to get early feedback from @szeiger so you don't waste a lot of time on changes he may not want in.

**Comment by rfranco** [comment]
@szeiger :question:

**Comment by szeiger** [comment]
I haven't looked at the changes yet. We're getting close to 3.0.0 and I wouldn't want to make major changes to the build process before that release.

- I'm against any automatic source code formatting
- Docs in a separate project could be a good idea. We didn't do it that way because we didn't have a multi-project build back then and a configuration seemed easier than modularizing into projects.
- I very much like the whole build to be defined in a single file. Many changes you have to make affect several sub-projects. Having to deal with multiple files just complicates things.

**Comment by szeiger** [comment]
Just a quick heads up: 3.0 will move Slick from package `scala.slick` to `slick` which means moving almost every file in the repo. This is the perfect opportunity to fix the project layout (i.e. move the main project `slick` into a subdirectiy and create another project for the docs)

**Comment by rfranco** [comment]
It's really good opportunity. How do you prefer to do that? 
So how i can help?

**Pull request closed without merging**
