### PR TITLE
correct the parsing logic between positive infinite and Instant.MAX (issue #2237)

### PR DESCRIPTION
**Pull request by janory**
Fix for this issue: https://github.com/slick/slick/issues/2237

### CODE REVIEW

**Comment by nafg** [comment]
@janory assigning to you to fix the test failures

**Comment by janory** [comment]
test

**Review by nafg — CHANGES_REQUESTED** [review]
Can you include a test that shows that this works (and was broken before)?

**Review by nafg — APPROVED** [review]

**Comment by nafg** [comment]
Thanks!

**Pull request merged**
