### PR TITLE
MS SQLServer specific UUID datatype implementation

### LINKED ISSUE #2291: SQLServer support for UUID is broken (wrong endianness)
Current SQLServerProfile implementation is using default `UUIDJdbcType` from [here](https://github.com/slick/slick/blob/b39dda861573fae05e82a51cf8df02416f8be45b/slick/src/main/scala/slick/jdbc/JdbcTypesComponent.scala#L435) with slight modifications. This doesn't really work as the bytes are converted the wrong way (which seems to be correct for other DB profiles, but not for SQLServer). It is pretty simple to test this comparing the parsed value and the string representation (if map to `String` instead of `UUID` in schema).

The correct way to [read](https://github.com/microsoft/mssql-jdbc/blob/09d35bfc2338f1fc7c41a958d1e627fa0d6a2b65/src/main/java/com/microsoft/sqlserver/jdbc/Util.java#L703) and [write](https://github.com/microsoft/mssql-jdbc/blob/09d35bfc2338f1fc7c41a958d1e627fa0d6a2b65/src/main/java/com/microsoft/sqlserver/jdbc/Util.java#L669) this data type could be checked in JDBC driver sources. They have dedicated utilities to make it compatible.

The code in question is licensed under MIT. If it is acceptable to contribute the code derived from MIT licensed sources I can try to compose a PR fixing this issue.

### PR DESCRIPTION
**Pull request by arixmkii**
Fixes #2291 

Changes compared to base type:
* allow literal support (the code from `PosgresProfile` as the format is compatible with SQLServer)
* `fromBytes` and `toBytes` reimplemented with Scala version of utilities found in mssql-jdbc driver of version 10.2.0
* `sqlType` changed to `java.sql.Types.BINARY`, this is questionable, it is `OTHER` in super type, but `VARBINARY` for Oracle. I see this datatype as binary with constant size of 16 bytes, so, selected this type, but I'm not an expert on JDBC internals.

The only significant change from Java code in mssql-jdbc is at line 466
```scala
      if (inputGUID.length != 16) return null
```

Original code throws exception, very specific one for SQLServer and I don't know if it is good to throw exceptions in this place in slick (probably not). Also, this is like a should never happen under normal operation scenario.

I tested it with modified playframework slick example application and with some other application, but don't know how to provide a good integration test for this (I read docs on testkit, but didn't manage catch up immediately).

### CODE REVIEW

**Comment by nafg** [comment]
Thanks!

Bonus points for a unit test ;)

**Comment by nafg** [comment]
Re testing, try to look at the existing suite of tests and see where something like this might fit inconspicuously ;)

But if you can't, it's ok.

**Comment by nafg** [comment]
@arixmkii any chance you could try to supply a test?

**Comment by arixmkii** [comment]
@nafg Will try to add it by Wednesday evening (Europe tz)

**Comment by nafg** [comment]
Thanks!

**Comment by arixmkii** [comment]
Saw this locally, when copied sql config to default one to run test. It seems that create/drop parts were not operational. I manually created DB, tests passed and DB was not deleted afterwards. Will try to understand this behavior later.

**Comment by arixmkii** [comment]
@nafg I believe I tracked it down. Added commit changing useless, but harmful drop sequence to useless and harmless. 
https://github.com/slick/slick/blob/b528b87bb2096e5d385e0b4f8cc6920a75710ba3/slick-testkit/src/main/scala/com/typesafe/slick/testkit/util/TestDB.scala#L240
Here it executes drop always before create and if DB doesn't exist, then it fails with the first one and doesn't create new DB. I replaced it with Print, but SELECT 1 might work as well.

Sorry for delay. Some other topics kicked in.

**Comment by nafg** [comment]
Thanks!

**Pull request merged**
