### PR TITLE
Update Scala 2.12 to 2.12.9

### PR DESCRIPTION
**Pull request by TimMoore**

### CODE REVIEW

**Comment by szeiger** [comment]
LGTM. I think it would be best to rebase this once https://github.com/slick/slick/pull/2050 has been merged. I wouldn't expect any problems from the 2.12.8 to 2.12.9 upgrade and the AppVeyor build is green but any ugly surprises of such an update would probably come from JDK compatibility or OSGi and these are not tested on AppVeyor.

**Comment by TimMoore** [comment]
I just rebased to pick up the Travis fix, but #2050 has not yet been merged.

**Comment by TimMoore** [comment]
Now rebased again on top of #2050.

**Comment by TimMoore** [comment]
There are a couple of failed jobs in Travis that look like transient download failures from Maven Central. This seems to be a big problem on Travis recently. Could a committer re-run those jobs?

**Pull request merged**
