### PR TITLE
PostgreSql code generator handling of `bpchar` column defaults. Tolerate...

### PR DESCRIPTION
**Pull request by gregor-rayman**
... more invalid defaults when `ignoreInvalidDefaults` is `true`. Fixes issue #1104
- PostgreSql reports the defaults for CHAR columns in the form 'abc'::bpchar. This was previously not handled correctly because the expected format was just 'abc'
- When generating the defaults, only MatchError and NumberFormatException were tolerable. In PostgreSql specifying NULL as a default for a NOT NULL column
   is valid (although the default is not usable). Now such unsuable default can be ignored when `ignoreInvalidDefaults` is `true` too.

I have tested the correct behavior with the following table:

``` sql
create table public.gentest (
  id integer primary key not null default nextval('gentest_id_seq'::regclass),
  c1 character(1) default 'a'::bpchar, -- correct default for a char(1) column
  c2 character(1) default 'ab'::bpchar, -- too long default for a char(1) column
  c3 character(3) default 'abc'::bpchar, -- correct default for a char(3) column
  c4 character(3) default 'ab'::bpchar, -- correct default for a char(3) column, will be 'ab ' after insert
  c5 character(3) default 'abcd'::bpchar, -- too long default
  c6 character varying(20) not null default NULL::character varying, -- invalid NULL default
  c7 character(1) default NULL::bpchar, -- correct null default (does not need to be specified)
  c8 character(1) default ''::bpchar, -- correct empty string (is not null in postgresql) default, will be ' ' after insert
  c9 character(1) not null default 'a'::bpchar, -- correct default for a not null char(1) column
  c10 character(1) not null default 'ab'::bpchar, -- too long default for a char(1) column
  c11 character(1) not null default ''::bpchar, -- correct default for a char(1) not null column, will be ' ' after insert
  c12 character(1) not null default NULL::bpchar -- invalid NULL default
);
```

### CODE REVIEW

**Comment by szeiger** [comment]
Thanks, looks like a useful change. Can you add a test case to GenerateMainSources.scala?

**Comment by gregor-rayman** [comment]
I will soon :)

**Comment by szeiger** [comment]
Any update on this?

**Comment by AtkinsChang** [comment]
New Postgres reports the defaults for negative numeric in the form `'-10::integer' now. It would be good to fix all the issues about default value with type together.

**Comment by stewSquared** [comment]
I suppose this should be closed, since #1582 is merged

**Comment by SethTisue** [comment]
closing for inactivity

**Pull request closed without merging**
