### PR TITLE
Resolve issue #1424

### PR DESCRIPTION
**Pull request by radsaggi**

### CODE REVIEW

**Comment by hvesalai** [comment]
This PR is failing with the following exception in travis. Can somebody take a look. Ping @radsaggi 

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `table_name`( id INT NOT NULL )' at line 1
```

**Comment by WellingR** [comment]
Seems to have been fixed in https://github.com/slick/slick/commit/4fb8faf4cd8defda5c3e0dccc2581d614b907231

**Comment by hvesalai** [comment]
Build restarted, but now there is a conflict in Build.scala. Somebody needs to rebase this on top of the latest master.

**Comment by WellingR** [comment]
@hvesalai What I meant to say is that a change which looks suspiciously similar to this change was already merged as part of https://github.com/slick/slick/commit/4fb8faf4cd8defda5c3e0dccc2581d614b907231
In addition #1424 has been closed already, so I think this PR is no longer needed

**Comment by SethTisue** [comment]
closing for inactivity

**Pull request closed without merging**
