### PR TITLE
[DON'T MERGE] Add imports to more manual pages

### LINKED ISSUE #1732: Document totally fails to describe the imports and how to use them
http://slick.lightbend.com/doc/3.1.0/queries.html

On this page it sets up the most basic example of an object mapping.  And yet, it totally fails to give you any imports!!!!  You have to go digging through google, and even then, it still a total mystery as to what works and what doesn't.  After two hours of messing about desperately attempting to get this working, I'm STILL getting a compile error.

This is the third or fourth time bootstrapping from scratch with Slick on a project, and every time I run into this same problem since slick 1.0.0.  At this point in my career journey, I just don't have time anymore to mess with this.  If it doesn't work out of the box, forget it.  DOA.

### PR DESCRIPTION
**Pull request by d6y**
Fixes #1732 

## This PR adds import information to the manual

This PR adds a note about imports to more pages: DBIO, Schemas, Queries, Schema Code Generation, and User-Defined Features.  It looks like this:

queries 2017-06-22 12-44-56

## This is done by referencing the example code

Rather than manually add the imports to the text, I thought it was safed to pull them in from the example source files. I've added a few more `//#imports` comments to do that.

## It's not perfect

A consequence is that the import notes aren't as nice as we might like. For example, in Schemas we note we're impoting `ClassTag`, but that's not used until the User-Defined Features page.  But both pages use the same code (`LiftEmbedding.scala`).  If we like this PR, a further step could be to have an example Scala file per page where this kind of thing happens.

I don't know if this PR is against the right branch. Perhaps it should be against master.

### CODE REVIEW

**Comment by trevorsibanda** [comment]
@d6y I think this should be merged into master?

**Comment by d6y** [comment]
@trevorsibanda yes, I'll see what happens if I try to move this PR to master.... 🤞

**Comment by d6y** [comment]
I have borked this PR.  I'll re-work it and open it as a new PR against master.

**Comment by d6y** [comment]
@trevorsibanda this PR is superseded by https://github.com/slick/slick/pull/1787

**Pull request closed without merging**
