### PR TITLE
Use 'for' instead of 'while' for some loops on 'JdbcTypesComponent.scala'

### PR DESCRIPTION
**Pull request by xavier-fernandez**

### CODE REVIEW

**Comment by cvogt** [comment]
@szeiger do you have a comment on this?

**Comment by cvogt** [comment]
no objection to merge this from my side

**Comment by Sumith1896** [comment]
+1 from me. But why is `for` preferred over `while`?

**Comment by xavier-fernandez** [comment]
In my opinion `for` is much easier to read and we avoid creating a `mutable` variable directly. 

The following web page explains that in a really nice way: http://blog.8thlight.com/colin-jones/2009/06/16/a-functional-refactoring-in-scala.html

**Comment by cvogt** [comment]
@xavier-fernandez I think there is potentially a performance concern, but I'd like to hear that from @szeiger

**Comment by xavier-fernandez** [comment]
@cvogt  I didn't know the result bytecode could be different between both approaches.

**Comment by djx314** [comment]
"for loop" in list is actually use map and orther methods when compile, and the map method is using "while loop", so I think use "while loop" is a bit faster, it's no need to change to for because the code here is easy to read(Just a simple loop).

**Comment by cvogt** [comment]
@djx314 good point, it calls `while`. In that case I think the abstraction over var/while wins over the costs a method call. Merging this.

**Comment by cvogt** [comment]
thx @xavier-fernandez

**Comment by djx314** [comment]
@cvogt In the code I show in scala <https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/immutable/List.scala#L373>
`0 until 8` will create a listLike object
`list.tail` will craete a new list, and this method will run 7 or 8 times. It means that it will create 7 or 8 new lists.
If you use "var/wile loop", these cost is zero. So if the code need hard speed, I prefer to use "whie loop" especially the while loop here is too simple.

**Comment by cvogt** [comment]
@djx314 thanks for the extra insight. I doubt it's a problem with the serialization of UUIDs.

**Comment by szeiger** [comment]
I apologize for not having looked at this earlier. I think this change should be reversed. There is no special optimization for these loops, at least in 2.11. This is in the innermost loop when reading large result sets, where performance trumps readability. A `for(i <- x until y)` loop creates exactly the code that you naively expect, including boxed integers and a separate class for the lambda:

```
$ cat fortest.scala
object ForTest {
  for(i <- 1 until 5) println(i)
}

$ scalac fortest.scala

$ javap -c -p ForTest$
Compiled from "fortest.scala"
public final class ForTest$ {
  public static final ForTest$ MODULE$;

  public static {};
    Code:
       0: new           #2                  // class ForTest$
       3: invokespecial #12                 // Method "<init>":()V
       6: return

  private ForTest$();
    Code:
       0: aload_0
       1: invokespecial #13                 // Method java/lang/Object."<init>":()V
       4: aload_0
       5: putstatic     #15                 // Field MODULE$:LForTest$;
       8: getstatic     #20                 // Field scala/runtime/RichInt$.MODULE$:Lscala/runtime/RichInt$;
      11: getstatic     #25                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
      14: iconst_1
      15: invokevirtual #29                 // Method scala/Predef$.intWrapper:(I)I
      18: iconst_5
      19: invokevirtual #33                 // Method scala/runtime/RichInt$.until$extension0:(II)Lscala/collection/immutable/Range;
      22: new           #35                 // class ForTest$$anonfun$1
      25: dup
      26: invokespecial #36                 // Method ForTest$$anonfun$1."<init>":()V
      29: invokevirtual #42                 // Method scala/collection/immutable/Range.foreach$mVc$sp:(Lscala/Function1;)V
      32: return
}
``

**Pull request merged**
