### PR TITLE
Update docs to include code generator with a config URI

### PR DESCRIPTION
**Pull request by stewSquared**

### CODE REVIEW

**Comment by cvogt** [comment]
LGTM

**Comment by stewSquared** [comment]
Huh. How could CI possibly have failed?

**Comment by cvogt** [comment]
haha, I almost merged and then I was like ... not let's wait for CI

**Comment by d6y** [comment]
Cool! I've not used that variant of `main` before.  Is that example URI with brackets...

```
"(url#slick.db.default)"
```
...a valid example @stewSquared?  

Otherwise, LGTM, and here's the output from `sbt make-site` ... 

schema code generation slick 3 2 0-snapshot documentation 2016-03-24 08-28-59

**Comment by stewSquared** [comment]
@d6y Ha, yeah. I found this in the source while trying to figure out how to use values from my application.conf rather than hardcoding into my build.

There should be no parens in the example URI -- thanks for catching that!

**Comment by stewSquared** [comment]
Should I squash these down to one commit?

**Comment by d6y** [comment]
@stewSquared I wouldn't worry about squashing for this change.

**Comment by d6y** [comment]
I see two LGTMs, so I'm merging....

**Pull request merged**
